### ISSUE TITLE
cyrl-en=tailed actually causes cyrl-en=motion-serifed, and related

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#1021]
As of 2021-05-19, in `dev` branch `cyrl-en=tailed` for italic style visually causes `cyrl-en=motion-serifed`. `dev` branch as of 2021-05-09 was fine.

1. I guess the root of the issue is the commit b5c113ac6c6a035b857f9ea27462596ec76877aa , causing two "variants" to reference the same 0x43D character.
```diff
 	select-variant 'cyrl/en' 0x43D (shapeFrom -- 'smcpH')
+	select-variant 'cyrl/en/reduced' 0x43D (shapeFrom -- 'smcpH')
```

2. Also, in the following fragment is `cyrl/en/reduced=motionSerifed` really valid? `tailed` has no top left serif in `sans` variant whereas `motionSerifed` has.
```toml
[prime.cyrl-en.variants.tailed]
rank = 2
description = "Cyrillic Lower En (`н`) with tail"
selector."cyrl/en" = "tailed"
selector."cyrl/en/reduced" = "motionSerifed"
```

**Comment by pv4** [comment]
@be5invis And what about making `cyrl/en/reduced=standardSmallCyrl` for `cyrl-en=tailed`? I tried fixing it in my build it seems to make characters mentioned in #1006 more consistent with "plain cyrl-en".

**Comment by be5invis** [comment]
Well, `cyrl/en/reduced` is the "base" of `ң`/`ӊ`/`ӈ`, so the tailed variant doesn't make sense for them, since they grow descender/hook.

**Comment by pv4** [comment]
> the tailed variant doesn't make sense for them

It would not if the tail were the only difference between `tailed` and `motionSerifed`

But if I use `cyrl-en=tailed` in non-slab version I get these en-like glyphs with top-left serif. It would be logical if `tailed` always caused the serif (please, do NOT do this) but currently that's not the case.

However, slab version should use `motionSerifed` for `cyrl/en/reduced`. I hate myself for asking this but would you consider making one more variant, `cyrl-en=motion-serifed-tailed`? This would solve the issue.

**Comment by be5invis** [comment]
@pv4 The current variant system is already doing this: if you assign `cyrl-en = "tailed"` then `cyrl/en/reduced` will look the same as `cyrl/en.motionSerifed`:

```toml
[prime.cyrl-en]
sampler = "н"
samplerExplain = "Cyrillic Lower En"
tag = "cv63"

[prime.cyrl-en.variants.standard]
rank = 1
description = "Cyrillic Lower En (`н`) with standard shape"
selector."cyrl/en" = "standardSmallCyrl"
selector."cyrl/en/reduced" = "standardSmallCyrl"

[prime.cyrl-en.variants.tailed]
rank = 2
description = "Cyrillic Lower En (`н`) with tail"
selector."cyrl/en" = "tailed"
selector."cyrl/en/reduced" = "motionSerifed"

[prime.cyrl-en.variants.motion-serifed]
rank = 3
description = "Cyrillic Lower En (`н`) with motion serifs"
selector."cyrl/en" = "motionSerifed"
selector."cyrl/en/reduced" = "motionSerifed"
```
