### ISSUE TITLE
TTC generation omits nonstandard weights and widths

### ISSUE THREAD

**Issue by sigprof** [be5invis/Iosevka#1026]
When building Iosevka v6.3.1 with `private-build-plans.toml` specifying some nonstandard weights and widths, the TTF files for these fonts are correctly generated in `dist/<name>/ttf/*.ttf`; however, when trying to build a TTC file for them (using the `super-ttc::<name>` target and `[collectPlans.<name>]`), the resulting TTC file in `dist/.super-ttc/<name>.ttc` does not contain any font variations which have a nonstandard weight or width.

A simple `private-build-plans.toml` which exhibits the bug:
```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-custom.weights.book]
shape = 450
menu  = 450
css   = 450

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-custom.slopes]
upright = "normal"
italic = "italic"

[buildPlans.iosevka-custom.widths.normal]
shape = 500
menu  = 5
css   = "normal"

[buildPlans.iosevka-custom.widths.extended]
shape = 600
menu  = 7
css   = "expanded"

[buildPlans.iosevka-custom.widths.ultraextended]
shape = 720
menu  = 9
css   = "ultraexpanded"

[collectPlans.iosevka-custom]
from = [ 'iosevka-custom' ]
```
Build commands:
```sh
npm install
npm run build -- ttf::iosevka-custom super-ttc::iosevka-custom
```
This builds 18 TTF files with the following font variations:
```
$ fc-scan -f '%{fullname}\n' dist/iosevka-custom/ttf/*.ttf | LC_ALL=C sort
Iosevka Custom
Iosevka Custom Bold
Iosevka Custom Bold Extended
Iosevka Custom Bold Extended Italic
Iosevka Custom Bold Italic
Iosevka Custom Bold Ultra-Extended
Iosevka Custom Bold Ultra-Extended Italic
Iosevka Custom Book
Iosevka Custom Book Extended
Iosevka Custom Book Extended Italic
Iosevka Custom Book Italic
Iosevka Custom Book Ultra-Extended
Iosevka Custom Book Ultra-Extended Italic
Iosevka Custom Extended
Iosevka Custom Extended Italic
Iosevka Custom Italic
Iosevka Custom Ultra-Extended
Iosevka Custom Ultra-Extended Italic
```
However, the super-TTC file contains only 8 font variations:
```
$ fc-scan -f '%{fullname}\n' dist/.super-ttc/iosevka-custom.ttc | LC_ALL=C sort
Iosevka Custom
Iosevka Custom Bold
Iosevka Custom Bold Extended
Iosevka Custom Bold Extended Italic
Iosevka Custom Bold Italic
Iosevka Custom Extended
Iosevka Custom Extended Italic
Iosevka Custom Italic
```
Apparently any font variations which have a nonstandard weight or width (not mentioned in `build-plans.toml`) are silently skipped when combining fonts into TTC files, and there is no way to override the top-level `weights` and `widths` tables from `private-build-plans.toml` without actually modifying `build-plans.toml`.
