### ISSUE TITLE
Add a new bolder weight called `Black`; increase font-weight range to <= 1000

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#1040]
**Describe the solution you'd like**
I would like to extend the weight range to 1000, and add a new weight called `Black` to the Iosevka font. 

Recent versions of the [CSS Fonts specification](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) allow for weight values between 1 and 1000, inclusive, whereas, currently Iosevka currently allows for weight values **between 100 and 900** inclusive, though (I heard) it can accept non-standard weight values.

Quoted from the above page:
> CSS Fonts Level 4 extends the syntax to accept **any number between 1 and 1000** and introduces Variable fonts, which can make use of this much finer-grained range of font weights.

**Describe alternatives you've considered**
We only need to edit `params/shape-weight.toml` and add the following section, just right below the `[shapeWeight.blend.900]` section. Here's what I mean:

```toml
[shapeWeight.blend.1000]
# we would need to edit the numbers below 
# (this is copied straight from `/shape-weight.toml`)
stroke = 114
contrast = 1.20
sb = 56
essx = 1.05
dotsize = 180
periodsize = 200

jut = 95
vjut = 200
smooth = 215
rbalance = 50
rbalance2 = 25
cthin = 0.75
cthinb = 0.5
```

If we're implementing this we have to change up the parameters above for these variables so to account for the bolder weight.

**Additional context**
The [Recursive Mono](https://www.recursive.design/) font has a CSS weight range between 300 and 1000. The weight here has ben set to its maximum, and here's how that looks like:

![2021-05-23 13_11_07-Recursive Sans   Mono](https://user-images.githubusercontent.com/16898444/119249073-76727d00-bbc8-11eb-8505-34a0e924da4b.png)
