### ISSUE TITLE
More handy width/side-bearings customization

### ISSUE THREAD

**Issue by dntzu** [be5invis/Iosevka#1181]
**Is your feature request related to a problem? Please describe.**
For now in custom builds there is no way to automatically build regular and extended width variants of font with the same glyph sizes because side bearing parameter is not a proportion but an exact value. So every build you have to manually adjust parameters by yourself.

**Describe the solution you'd like**
Adding proportional side-bearing parameter while keeping standard one. Proportional value should override standard if set.

**Describe alternatives you've considered**
Ability to set side-bearing value for each specified width separately. Moving `sb` parameter from metric to width block.

**Additional context**
By the way can anyone explain me how the emu unit works? Especially with `sb` parameter. I thought I will be able to get the same glyph size on extended 600em width by multiplying `sb` with 1.2 but it didn't worked and so I have to set the value approximately.

**Comment by be5invis** [comment]
There's already a mechanism to use a scale in `metric-override` (as well as using an offset):

```toml
[buildPlans.iosevka-custom.metric-override.multiplies]
sb = 1.0625

[buildPlans.iosevka-custom.metric-override.adds]
sb = 15
```

**Comment by dntzu** [comment]
@be5invis and again it just works thank you. But I still wonder why manual value multiplication didn't work the same way?

**Comment by be5invis** [comment]
Let me introduce expression-style metric override. Now, you can do this:

```toml
[buildPlans.iosevka-custom.metric-override]
sb = 'blend(width, [500, 60], [600, 110])'
```

This configuration will set sidebearing to `60` when width is at `500`, and to `110` when width is at `600`.

Closing as fixed.
