### ISSUE TITLE
Add ability to select which slopes/weights/widths to build without overriding defaults

### ISSUE THREAD

**Issue by dieggsy** [be5invis/Iosevka#1215]
**Is your feature request related to a problem? Please describe.**
Currently to select only specific slopes, weights, or widths to build, you have to specify a lot of extra additional values (e.g. shape). I don't see an easy way of just selecting the defaults, and should the defaults change, they'd probably be overridden by the private-build-plans.toml file.

**Describe the solution you'd like**
It would be nice if I could specify a simple list of slopes/weight/widths, like before:
```toml
[buildPlans.iosevka-custom.slopes]
upright = "normal"
italic = "italic"
```

**Describe alternatives you've considered**
None that I know of short of having to manually specify values?

**Comment by be5invis** [comment]
I'd rather use things like
```toml
[buildPlans.iosevka-exp.weights]
regular = "default.regular"

[buildPlans.iosevka-exp.widths]
normal = "default.normal"

[buildPlans.iosevka-exp.slopes]
upright = "default.upright"
```
