### ISSUE TITLE
How to properly build Iosevka as quasi-proportional, but WITHOUT coding ligatures?

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1259]

**Comment by be5invis** [comment]
```toml
spacing = "quasi-proportional"
no-ligation = true
```
