### ISSUE TITLE
I can't find "Medium Bold" fonts

### ISSUE THREAD

**Issue by Sleepful** [be5invis/Iosevka#1262]
installed with brew

I'm using Kitty terminal so this command tells me the available fonts:

```
kitty list-fonts | grep -i 'Ios' | grep -i 'bold'
```
There are no bold fonts for "Medium" or "Light" families.

Example:

```
$ kitty list-fonts | egrep -i 'Iosevka Medium|Iosevka Light'
    Iosevka Light
    Iosevka Light Extended
    Iosevka Light Extended Italic
    Iosevka Light Extended Oblique
    Iosevka Light Italic
    Iosevka Light Oblique
    Iosevka Medium
    Iosevka Medium Extended
    Iosevka Medium Extended Italic
    Iosevka Medium Extended Oblique
    Iosevka Medium Italic
    Iosevka Medium Oblique
```

**Comment by be5invis** [comment]
Well, `Medium` is a **Weight**, so its “bold” doesn't make sense.

**Comment by Sleepful** [comment]
So bold is the same across all weights? it looks a little jarring if you are using Light weight for example

**Comment by be5invis** [comment]
“Bold” is a **weight**. A font cannot have two weights.

If you want to make the default weight a little thicker, you can customize it like this.

```toml
[buildPlans.iosevka-custom.weights.regular]
shape = 500 # Make shape thicker
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 800 # Make shape thicker
menu = 700
css = 700
```
