### ISSUE TITLE
Neck in capital S gets thinner under shape greater than 600

### ISSUE THREAD

**Issue by cssobral2013** [be5invis/Iosevka#1265]
Examples for Bold/Bold Italic are shown below.
![Sem título](https://user-images.githubusercontent.com/19995437/146658223-655001e5-9394-4b69-84d5-6be9d3be409b.png)

A solution for this would be implementing independent essoverrides on upper and lowercase.

**Comment by cssobral2013** [comment]
@be5invis - Now, to end this conversation, how do I set different essRatios for upper and lowercase?

**Comment by cssobral2013** [comment]
@be5invis - Nevermind the previous post, I figured it out myself.

**Comment by be5invis** [comment]
@cssobral2013 

```toml
[buildPlans.iosevka-custom.metric-override]
essRatioUpper = 1.25 # overrides default essRatio for uppercase
essRatioLower = 1.1  # overrides default essRatio for lowecase
```
