### ISSUE TITLE
Provide parameter to adjust radius of characters with o glyph

### ISSUE THREAD

**Issue by admacro** [be5invis/Iosevka#1313]
Hi,

I'd like to suggest a customization feature which is to be able to adjust the radius of the o glyph in characters like abcdegopq and their capitalized versions. Currently, these letters give a rather squarish look and feel if built with Extended as Normal option (width = 600).
```toml
[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.metric-override]
sb = 75
cap = 700
xheight = 500
```
<img width="205" alt="Screen Shot 2022-02-22 at 10 58 29" src="https://user-images.githubusercontent.com/693322/155055393-10f87b45-28bf-403b-ba07-20d1beedbb36.png"> <img width="205" alt="Screen Shot 2022-02-22 at 10 58 42" src="https://user-images.githubusercontent.com/693322/155055398-c05bcb77-cdde-49e4-b961-2939d532b485.png">
