### ISSUE TITLE
Is there a way to make glyphs more "curved"?

### ISSUE THREAD

**Issue by hydino2085143** [be5invis/Iosevka#1322]
I've generated a custom Iosevka font, using 3 metric override parameters:
```
xHeight = 515
sb = 50
essRatio = 1.20
```

Currently certain curved letters such as `a`, `b`, `d`, etc. look too "squarish" for my taste.
![image](https://user-images.githubusercontent.com/46134462/156612561-9d5663e4-a313-4c18-b56c-451e781cc683.png)

Is there some parameter I can change to make it look more curved?

**Comment by aplab** [comment]
Can you show your own private-build-plans.toml here?

**Comment by hydino2085143** [comment]
<details>
<summary>private-build.plans.toml</summary>

```toml
[buildPlans.iosevka-derp]
family = "Iosevka Derp"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-derp.variants.design]
capital-d = "more-rounded-serifless"
capital-k = "symmetric-touching-serifless"
capital-q = "crossing"
f = "flat-hook"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
t = "flat-hook"
four = "closed-non-crossing"
eight = "two-circles"
brace = "straight"
paren = "large-contour"
dollar = "open"
cent = "open"
percent = "dots"
lig-ltgteq = "slanted"

[buildPlans.iosevka-derp.variants.italic]
e = "flat-crossbar"
f = "flat-hook"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
t = "flat-hook"

  [buildPlans.iosevka-derp.ligations]
  inherits = "dlig"

[buildPlans.iosevka-derp.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-derp.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-derp.widths.normal]
shape = 540
menu = 5
css = "normal"

[buildPlans.iosevka-derp.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-derp.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-derp.metric-override]
xHeight = 515
sb = 50
essRatio = 1.20
```

</details>
