### ISSUE TITLE
Building without ligatures not working

### ISSUE THREAD

**Issue by FerdinandRau** [be5invis/Iosevka#1333]
I tried to build Iosevka without ligatures, but they still show up in iTerm2 and VS Code.
My `private-build-plans.toml` looks like this:

```toml
# Generated using Iosevka Customizer

[buildPlans.iosevka-term]
family = "Iosevka Term"
no-cv-ss = true
no-ligation = true
serifs = "sans"
spacing = "fontconfig-mono"

[buildPlans.iosevka-term.variants.design]
asterisk = "hex-low"
percent = "rings-continuous-slash"
underscore = "low"

[buildPlans.iosevka-term.weights.regular]
css = 400
menu = 400
shape = 400

[buildPlans.iosevka-term.weights.bold]
css = 700
menu = 700
shape = 700

[buildPlans.iosevka-term.widths.normal]
css = "normal"
menu = 5
shape = 600

[buildPlans.iosevka-term.slopes.upright]
angle = 0
css = "normal"
menu = "upright"
shape = "upright"

[buildPlans.iosevka-term.slopes.italic]
angle = 9.4
css = "italic"
menu = "italic"
shape = "italic"
```
- macOS 12.3.1
- Node.js 17.8.0
- build command: `npm run build -- contents::iosevka-term`
- no other source files were modified
