### ISSUE TITLE
Customization isn't applied: weights filter doesn't work; ligations variant "javascript" gets ignored

### ISSUE THREAD

**Issue by OnkelTem** [be5invis/Iosevka#1340]
I use the following config:

```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-custom.ligations]
  inherits = "javascript"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"
```

and docker for building my font:
```
$ docker run -it -v $(pwd):/build avivace/iosevka-build ttf::iosevka-custom
```

But on the output I get all weights including thin and extrabold.

Another problem is that triple `=` (`===`) results to two lines while according to the "javascript" variants template there should be three.

![image](https://user-images.githubusercontent.com/114060/164936434-839e0924-9585-4711-85cf-1f7f4aaf18a9.png)

Also I noticed that two long lines in long = have gaps inside. They are distinguishable on the screenshot.

The third problem is that `Width Option` isn't applied as well. Changing it to `Standard/Extended` doesn't make any difference.

My VSCode font config:

```
  "editor.fontFamily": "Iosevka",
  "editor.fontLigatures": true,
  "editor.fontSize": 16,
```

P.S. Why there goes an indent in the `  [buildPlans.iosevka-custom.ligations]` line here?

![image](https://user-images.githubusercontent.com/114060/164936684-d60e3b82-3ebd-4fcd-8f40-a8a7676e17bc.png)
