### ISSUE TITLE
User variant inheritance

### ISSUE THREAD

**Issue by jdknezek** [be5invis/Iosevka#1345]
**Is your feature request related to a problem? Please describe.**
When building multiple families of fonts with the same variants, `private-build-plans.toml` contains a lot of duplicate data, and can be prone to copy-paste errors, especially the more families you are building. That said, this is merely nice-to-have.

**Describe the solution you'd like**
It would be nice if in `private-build-plans.toml` you could inherit variants from another user variant, e.g.

```toml
[buildPlans.my-build-normal.variants.design]
capital-a = "straight-serifless"
capital-b = "standard-serifless"
# etc.

[build-plans.my-build-slab.variants]
inherits = "my-build-normal"
```
