### ISSUE TITLE
Provide quasi-proportional webfont variant as part of releases

### ISSUE THREAD

**Issue by pinpox** [be5invis/Iosevka#1385]
**Is your feature request related to a problem? Please describe.**
I have not been able to find the quasi-proportional variant webfont variant in the releases. I would like to use the quasi-proportional variant of iosevka webfont.

**Describe the solution you'd like**
Add iosevka webfont as quasio-proportional with and without expanded attribute.

**Describe alternatives you've considered**
building it myself

**Additional context**
To avoid confusion I'm talking about the variant build with a plan like this
```toml
[buildPlans.iosevka-qp]
family = "Iosevka QP"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true
```
using 
```
npm run build -- contents::iosevka-custom
```
to get the `webfont` (with `.css`) in additon to the `ttf`
