### ISSUE TITLE
Move Etoile/Aile design to variants

### ISSUE THREAD

**Issue by vincentbernat** [be5invis/Iosevka#1464]
**Is your feature request related to a problem? Please describe.**
When customizing Etoile or Aile, we need to copy/paste their design from `build-plans.toml`. Etoile is quite simple, but Aile is more comprehensive.

**Describe the solution you'd like**
Moving their design to `variants.toml` would allow easier customization and it would continue to work through updates.

**Comment by be5invis** [comment]
Well there's build plans called "Iosevka QP"/"QPE". They behave much like Aile/Etoile but without variant overrides.

```toml
[buildPlans.iosevka-QP]
family = "Iosevka QP"
desc = "Customizer Preview Only Quasi-proportional Sans"
spacing = "quasi-proportional"
export-glyph-names = false

[buildPlans.iosevka-QP-slab]
family = "Iosevka QP Slab"
desc = "Customizer Preview Only Quasi-proportional Slab"
serifs = 'slab'
spacing = "quasi-proportional"
export-glyph-names = false

[buildPlans.iosevka-QPE]
family = "Iosevka QPE"
desc = "Customizer Preview Only Quasi-proportional-extension-only Sans"
spacing = "quasi-proportional-extension-only"
export-glyph-names = false

[buildPlans.iosevka-QPE-slab]
family = "Iosevka QPE Slab"
desc = "Customizer Preview Only Quasi-proportional-extension-only Slab"
serifs = 'slab'
spacing = "quasi-proportional-extension-only"
export-glyph-names = false
```
