### ISSUE TITLE
Any way to build ligatures as single characters (e.g. Private Use Area)?

### ISSUE THREAD

**Issue by mrkgnao** [be5invis/Iosevka#167]
I've tried to play around with inserting `save` statements in the PatEL code, but it's pretty tough going. 

My objective is to get something like the Fira Code [emacs workaround](https://github.com/tonsky/FiraCode/wiki/Setting-up-Emacs) going. Some help would be appreciated here. Iosevka is delicious, but I only get to enjoy the ligatures in Firefox. :)

**Comment by be5invis** [comment]
But, Iosevka have arbitrary-length ligatures like `------------------------------------>`
How to handle this?

**Comment by be5invis** [comment]
And, `save` can be ONLY used inside a `sketch` block.

**Comment by be5invis** [comment]
@mrkgnao Do you mean this?

![image](https://cloud.githubusercontent.com/assets/240091/24343309/60622934-12f8-11e7-9219-08ac10b14142.png)

I've added config terms in `parameters.toml`:

```toml
# Compatibility PUA ligatures
[[iosevka.compLig]]
unicode = 57670 # 0xE146
featureTag = 'calt'
sequence = '>=>'

[[iosevka.compLig]]
unicode = 57676 # 0xE14C
featureTag = 'XV00'
sequence = '<*>'

[[iosevka.compLig]]
unicode = 57681 # 0xE151
featureTag = 'XV00'
sequence = '<!--'
```

**Comment by be5invis** [comment]
And if you REALLY want that...

![image](https://cloud.githubusercontent.com/assets/240091/24343710/73fd8d7e-12fa-11e7-9b78-d0ab0bb05344.png)

```toml
[[iosevka.compLig]]
unicode = 57682 # 0xE152
featureTag = 'XV00'
sequence = '------------->'
```
