### ISSUE TITLE
How are we supposed to use the new buildup-based variant system?

### ISSUE THREAD

**Issue by wimstefan** [be5invis/Iosevka#1745]
I'm using the `dev` branch and since the (partial) introduction of the new buildup-based variant system I get this kind of error messages:
```log
× Error Unhandled exception when building "Builtin::File::dist/iosevka-artesanal/ttf-unhinted/iosevka-artesanal-regular.ttf":
 Error: Error: Composite {user} cannot be resolved: m,earless-single-arch-short-leg.
    at Composite.decompose (file:///usr/local/src/Tools/x11/Iosevka-tools/Iosevka-dev.git/font-src/support/variant-data.mjs:182:19)
    at Composite.resolve (file:///usr/local/src/Tools/x11/Iosevka-tools/Iosevka-dev.git/font-src/support/variant-data.mjs:197:39)
    at Module.apply (file:///usr/local/src/Tools/x11/Iosevka-tools/Iosevka-dev.git/font-src/support/variant-data.mjs:19:17)
    at createParaImpl (file:///usr/local/src/Tools/x11/Iosevka-tools/Iosevka-dev.git/font-src/index.mjs:52:15)
    at reinit (file:///usr/local/src/Tools/x11/Iosevka-tools/Iosevka-dev.git/font-src/index.mjs:64:16)
    at main (file:///usr/local/src/Tools/x11/Iosevka-tools/Iosevka-dev.git/font-src/index.mjs:23:67)
    at ChildProcess.<anonymous> (/usr/local/src/Tools/x11/Iosevka-tools/Iosevka-dev.git/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:511:28)
    at emit (node:internal/child_process:944:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```
Has the format in the `build-plans.toml` changed? I can't find any information about it.
Or is it simply a question of leaning back and wait until the switch to the new system is finished?

<details>
<summary>This is my `private-build-plans.toml`</summary>

```toml
[buildPlans.iosevka-artesanal]
family = 'Iosevka Artesanal'
spacing = 'term'
no-cv-ss = 'false'
export-glyph-names = 'true'
[buildPlans.iosevka-artesanal.variants.design]
capital-a = 'curly-top-serifed'
capital-b = 'standard-interrupted-bilateral-serifed'
capital-d = 'more-rounded-unilateral-serifed'
capital-e = 'top-left-serifed'
capital-f = 'top-left-serifed'
capital-g = 'toothless-corner-serifless-hooked'
capital-h = 'top-left-serifed'
capital-i = 'short-serifed'
capital-j = 'serifed-symmetric'
capital-k = 'curly-top-left-serifed'
capital-l = 'motion-serifed'
capital-m = 'hanging-motion-serifed'
capital-n = 'asymmetric-motion-serifed'
capital-p = 'open-motion-serifed'
capital-q = 'open-swash'
capital-r = 'curly-open-motion-serifed'
capital-s = 'bilateral-serifed'
capital-u = 'toothless-corner-unilateral-motion-serifed'
capital-v = 'curly-motion-serifed'
capital-w = 'straight-vertical-sides-motion-serifed'
capital-x = 'curly-motion-serifed'
capital-y = 'curly-motion-serifed'
capital-z = 'cursive-with-horizontal-crossbar'
a = 'double-storey-toothless-corner'
b = 'toothless-corner-serifless'
d = 'toothed-serifed'
e = 'rounded'
f = 'flat-hook-diagonal-tailed-crossbar-at-x-height'
g = 'single-storey-earless-corner-flat-hook'
h = 'straight-top-left-serifed'
i = 'diagonal-tailed'
j = 'diagonal-tailed-serifless'
k = 'symmetric-connected-top-left-and-bottom-right-serifed'
l = 'diagonal-tailed'
m = 'earless-single-arch-short-leg'
n = 'earless-corner-straight-serifless'
r = 'corner-hooked'
s = 'bilateral-serifed'
t = 'diagonal-tailed-short-neck2'
u = 'toothless-corner-serifless'
v = 'cursive-serifed'
w = 'cursive-serifed'
x = 'curly-motion-serifed'
y = 'cursive-flat-hook-serifless'
z = 'cursive-with-horizontal-crossbar'
eszet = 'traditional-flat-hook'
digit-form = 'old-style'
zero = 'tall-slashed-cutout'
two = 'straight-neck'
three = 'flat-top'
four = 'open'
five = 'vertical-upper-left-bar'
six = 'straight-bar'
seven = 'bend-serifed'
eight = 'crossing-asymmetric'
nine = 'straight-bar'
ampersand = 'flat-top'
asterisk = 'penta-high'
at = 'short'
bar = 'force-upright'
caret = 'high'
dollar = 'interrupted-cap'
number-sign = 'slanted-open'
pilcrow = 'high'
tilde = 'high'
lig-equal-chain = 'without-notch'
[buildPlans.iosevka-artesanal.metric-override]
xHeight = 540
leading = 1150
onumZeroHeightRatio = '1.2'
[buildPlans.iosevka-artesanal.ligations]
inherits = 'dlig'
disables = ['ltgt-slash-tag']
[buildPlans.iosevka-artesanal.widths.normal]
shape = 520
menu  = 5
css   = 'normal'
[buildPlans.iosevka-artesanal.weights.regular]
shape = 400
menu  = 400
css   = 400
[buildPlans.iosevka-artesanal.weights.book]
shape = 450
menu  = 450
css   = 450
[buildPlans.iosevka-artesanal.weights.semibold]
shape = 600
menu  = 600
css   = 600
[buildPlans.iosevka-artesanal.weights.bold]
shape = 700
menu  = 700
css   = 700
[buildPlans.iosevka-artesanal.weights.extrabold]
shape = 800
menu  = 800
css   = 800
[buildPlans.iosevka-artesanal.weights.heavy]
shape = 900
menu  = 900
css   = 900
[buildPlans.iosevka-artesanal.weights.extraheavy]
shape = 1000
menu  = 1000
css   = 1000
[buildPlans.iosevka-artesanal.slopes.upright]
angle = 2.4
shape = 'upright'
menu  = 'upright'
css   = 'normal'
[buildPlans.iosevka-artesanal.slopes.italic]
angle = 6.4
shape = 'italic'
menu  = 'italic'
css   = 'italic'
```

</details>
