### ISSUE TITLE
Provide a way or make hook in **hooked** `r` variant more destinct with smaller sizes

### ISSUE THREAD

**Issue by kchibisov** [be5invis/Iosevka#1768]
When using font size of 14px the hook on `r` hooked variants is only distinct when the glyph is extra bold. As an example I'd attach it compared to `Fira Mono`. The issue was testing in alacritty on linux, but the font looks exactly the same in `firefox` on the same system.

![picture](https://github.com/be5invis/Iosevka/assets/27620401/ce2d4a57-9083-4e47-993a-75d71be81501)

The used iosevka was font is a custom built with the following plan changing the metrics. 
The version is 23.0.
Os: NixOS, freetype 2.13, subpixel AA is being used.

```toml
[buildPlans.iosevka-custom.weights.regular]
shape = 600
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 800
menu = 700
css = 700

[buildPlans.iosevka-custom.weights.extrabold]
shape = 875
menu = 800
css = 800

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 7
css = "normal"

[buildPlans.iosevka-custom.metric-override]
leading = 1250
xHeight = 520
cap = 690
parenSize = 840
ascender = 750
symbolMid = 340
sb = "default_sb * 1.025"
```

And the fontconfig options being applied on my system
<details>

```
+ /etc/fonts/conf.d/00-nixos-cache.conf: No description
+ /etc/fonts/conf.d/10-hinting-slight.conf: Set hintslight to hintstyle
+ /etc/fonts/conf.d/10-nixos-rendering.conf: No description
+ /etc/fonts/conf.d/10-scale-bitmap-fonts.conf: Bitmap scaling
+ /etc/fonts/conf.d/11-lcdfilter-default.conf: Use lcddefault as default for LCD filter
+ /etc/fonts/conf.d/20-unhint-small-vera.conf: Disable hinting for Bitstream Vera fonts when the size is less than 8ppem
+ /etc/fonts/conf.d/30-metric-aliases.conf: Set substitutions for similar/metric-compatible families
+ /etc/fonts/conf.d/40-nonlatin.conf: Set substitutions for non-Latin fonts
+ /etc/fonts/conf.d/45-generic.conf: Set substitutions for emoji/math fonts
+ /etc/fonts/conf.d/45-latin.conf: Set substitutions for Latin fonts
+ /etc/fonts/conf.d/48-spacing.conf: Add mono to the family when spacing is 100
+ /etc/fonts/conf.d/49-sansserif.conf: Add sans-serif to the family when no generic name
+ /home/kchibisov/.config/fontconfig/conf.d/10-hm-fonts.conf: No description
+ /etc/fonts/conf.d/50-user.conf: Load per-user customization files
+ /etc/fonts/local.conf: No description
+ /etc/fonts/conf.d/51-local.conf: Load local customization file
+ /etc/fonts/conf.d/52-nixos-default-fonts.conf: No description
+ /etc/fonts/conf.d/53-nixos-reject-type1.conf: No description
+ /etc/fonts/conf.d/53-no-bitmaps.conf: No description
+ /etc/fonts/conf.d/60-generic.conf: Set preferable fonts for emoji/math fonts
+ /etc/fonts/conf.d/60-latin.conf: Set preferable fonts for Latin
+ /etc/fonts/conf.d/65-fonts-persian.conf: No description
+ /etc/fonts/conf.d/65-nonlatin.conf: Set preferable fonts for non-Latin
+ /etc/fonts/conf.d/69-unifont.conf: No description
+ /etc/fonts/conf.d/80-delicious.conf: No description
+ /etc/fonts/conf.d/90-synthetic.conf: No description
+ /etc/fonts/fonts.conf: Default configuration file
```

</details>

--

Ps, it's likely not a bug, but I find it weird that making font bolder extends the hook to the bottom, so it's getting more distinct...
