### ISSUE TITLE
Detected broken geometry when processing mCrossedTail.serifless in custom build

### ISSUE THREAD

**Issue by jasyip** [be5invis/Iosevka#1882]
Describe your problem here. Provide pictures and files if necessary.

When building a custom variant, I get this unexpected error:
```
 [ACTION] Create TTF 'dist/lj-iosevka-aile/ttf-unhinted/lj-iosevka-aile-semi-condensedheavyoblique.ttf'
Detected broken geometry when processing mCrossedTail.serifless
Error:  Target Error Error: Error: NaN angle detected.
    at NormalRectifier.arcTo (file:///home/runner/work/ljs-iosevka/ljs-iosevka/font-src/support/geometry/spiro-expand.mjs:129:11)
    at collectSpiroArcs (/home/runner/work/ljs-iosevka/ljs-iosevka/node_modules/.pnpm/spiro@3.0.0/node_modules/spiro/lib/index.js:448:12)
    at Module.spiroToArcsOnContext (/home/runner/work/ljs-iosevka/ljs-iosevka/node_modules/.pnpm/spiro@3.0.0/node_modules/spiro/lib/index.js:480:16)
    at SpiroExpander.initializeNormals (file:///home/runner/work/ljs-iosevka/ljs-iosevka/font-src/support/geometry/spiro-expand.mjs:21:11)
    at DiSpiroGeometry.expand (file:///home/runner/work/ljs-iosevka/ljs-iosevka/font-src/support/geometry/index.mjs:153:12)
    at DiSpiroGeometry.asContours (file:///home/runner/work/ljs-iosevka/ljs-iosevka/font-src/support/geometry/index.mjs:126:29)
    at CombineGeometry.asContours (file:///home/runner/work/ljs-iosevka/ljs-iosevka/font-src/support/geometry/index.mjs:337:25)
    at TransformedGeometry.asContours (file:///home/runner/work/ljs-iosevka/ljs-iosevka/font-src/support/geometry/index.mjs:268:31)
    at SimplifyGeometry.asContours (file:///home/runner/work/ljs-iosevka/ljs-iosevka/font-src/gen/finalize/glyphs.mjs:104:30)
    at TransformedGeometry.asContours (file:///home/runner/work/ljs-iosevka/ljs-iosevka/font-src/support/geometry/index.mjs:268:31)
    at ChildProcess.<anonymous> (/home/runner/work/ljs-iosevka/ljs-iosevka/node_modules/.pnpm/verda@1.11.0/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (node:events:514:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```
In the past, my builds were successful. But this time, after adding a semi-condensed width, the build fails.

---

* Your font version: (Release or git, version)
A custom build based on verson 25.1.1
* Your font variant:
A sans variant
* Your operating system (name and version):
GitHub actions ubuntu runner
* Your application using Iosevka: 

If you have problem when building Iosevka, please provide these information:

* Your Node.js version:
NodeJS 20.5.0/pnpm 8.6.11
* Your `params/parameters.toml`, paste if modified:
  ```
  paste here
  ```
* Your `build-plans.toml`, paste if modified:
  ```
  paste here
  ```
* Your `private-build-plans.toml`, if present:
```toml
[buildPlans.lj-iosevka-aile]
family = "LJ's Iosevka Aile"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = false
export-glyph-names = true


[buildPlans.lj-iosevka-aile.variants.design]
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-q = "crossing-baseline"
c = "unilateral-serifed"
g = "double-storey"
i = "serifed-flat-tailed"
l = "serifed-flat-tailed"
m = "short-leg-serifless"
q = "tailed-serifless"
y = "curly-turn-serifless"
long-s = "bent-hook-tailed"
eszet = "sulzbacher-tailed"
lower-delta = "flat-top"
cyrl-capital-zhe = "straight"
cyrl-zhe = "straight"
cyrl-yery = "corner-tailed"
zero = "slashed"
one = "base-flat-top-serif"
seven = "curly-serifless"
nine = "open-contour"
underscore = "above-baseline"
brace = "curly-flat-boundary"
ampersand = "et-tailed"
at = "threefold-tall"
dollar = "through-cap"
percent = "rings-continuous-slash"
partial-derivative = "curly-bar"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"


[buildPlans.lj-iosevka-aile.ligations]
enables = [
    "arrow-l",
    "arrow-r",
    "counter-arrow-l",
    "counter-arrow-r",
    "trig",
    "tildeeq",
    "ltgt-diamond-tag",
    "kern-dotty",
    "kern-bars",
    "logic",
    "llgg",
    "llggeq",
    "brace-bar",
    "brack-bar",
]




[buildPlans.lj-iosevka-aile.widths.semi-condensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.lj-iosevka-aile.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.lj-iosevka-aile.widths.semi-extended]
shape = 547
menu = 6
css = "semi-expanded"

[buildPlans.lj-iosevka-aile.widths.extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.lj-iosevka-aile.widths.ultra-extended]
shape = 720
menu = 9
css = "ultra-expanded"

```
* The detailed error log:

[logs_185.zip](https://github.com/be5invis/Iosevka/files/12216642/logs_185.zip)

Here's my GitHub Actions workflow, if it helps (my workflow file has always worked in the past, but not this time for some reason):

```yaml
name: build fonts
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Run Git LFS
      #   run: git lfs install
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Configure PNPM settings
        run: |
          pnpm config set progress false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-


      - name: Install dependencies
        run: pnpm install


      - name: Install ttfautohint
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ttfautohint

      - name: Build Font
        run: pnpm run build -- ttf::${{ matrix.font-name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.font-name }}"
          path: "dist/${{ matrix.font-name }}"
          if-no-files-found: error
          retention-days: 90

    strategy:
      # max-parallel: 1
      matrix:
        font-name: ["lj-iosevka-term", "lj-iosevka-fcmono", "lj-iosevka-aile", "lj-iosevka-etoile"]
```
