### ISSUE TITLE
Spacing/position of arrow characters in v28.0.0?

### ISSUE THREAD

**Issue by we3geeks** [be5invis/Iosevka#2121]
I'm unsure if this is a problem introduced in v28 or in the customizer. I'm using a version of Iosevka with "terminal" spacing for my terminal apps on macOS and noticed a change when I built a new version of customized versions with the release of Iosevka v28: the "arrow" characters returned for wind direction from `wttr.in` are misaligned in v28 where they are not in the version I previously built from Iosevka v27.3.5 (and earlier).

Both examples here built with node v21.4.0.

Private build plan for v27.3.5:
```toml
[buildPlans.iosevka-terminal]
family = "Iosevka Terminal"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.iosevka-terminal.variants]
  inherits = "ss14"

    [buildPlans.iosevka-terminal.variants.design]
    zero = "tall-slashed"

[buildPlans.iosevka-terminal.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-terminal.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-terminal.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-terminal.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-terminal.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-terminal.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
```

... and font in use in macOS Terminal app (expected; note position of arrow before "2"):
<img width="682" alt="Screenshot 2023-12-17 at 7 38 46 AM" src="https://github.com/be5invis/Iosevka/assets/2390335/b2b858e8-4c67-4275-ba27-156934dc9866">

Private build plan for v28.0.0:
```toml
[buildPlans.IosevkaTerminal]
family = "Iosevka Terminal"
spacing = "Terminal"
serifs = "Sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaTerminal.variants]
  inherits = "ss14"

    [buildPlans.IosevkaTerminal.variants.design]
    zero = "tall-slashed"

[buildPlans.IosevkaTerminal.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaTerminal.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaTerminal.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaTerminal.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaTerminal.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaTerminal.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
```
... and font in use in macOS Terminal app (note position of arrow before "2"):
<img width="682" alt="Screenshot 2023-12-17 at 7 37 52 AM" src="https://github.com/be5invis/Iosevka/assets/2390335/74990e85-9a09-4687-845e-5e5344d1c857">

I see this in both macOS's Terminal and in Warp, so it doesn't appear to be specific to Terminal.
