### ISSUE TITLE
Can slash ligatures (`</ </> /> /* */ \/ /\`) coexist with the FRAC feature?

### ISSUE THREAD

**Issue by AndydeCleyre** [be5invis/Iosevka#2130]
I initially [reported reported this in the tracker for Wezterm](https://github.com/wez/wezterm/issues/4711), which may be the only place I can confidently set the FRAC feature. I have it set in fontconfig as well, but I don't think it has any noticeable effect.

In my wezterm config (fully pasted at the original issue), I have set:

```lua
harfbuzz_features = { 'kern', 'liga', 'clig', 'thnd', 'frac', 'txtr' },
```

I don't think `txtr` is working, but I'm ok with that.

With this configuration, running the following command in Zsh appears as below (the lower half is Wezterm):

```console
$ print -rlP -- '-<< --< -<- <-- <--- <<- <- -> ->> --> ---> ->- >- >>=' '=<< =< =<= <== <=== <<= <= => =>> ==> ===> =>= >= >>=' '<-> <--> <---> <----> <=> <==> <===> <====> :: ::: __' '<~~ %F{red}</ </> />%f ~~> == != %F{blue}/= ~=%f <> === !== !=== %F{blue}=/= =!=%f' '<: := *= *+ <* <*> *> <| <|> |> <. <.> .> +* =* =: :>' '(* *) %F{red}/* */%f [| |] {| |} ++ +++ %F{red}\/ /\%f \- -| <!-- <!---'
```

![image](https://github.com/be5invis/Iosevka/assets/1787385/ff6286d0-25ac-4600-8fe2-0c74013845cc)

Those red bits (`</ </> /> /* */ \/ /\`) do show up as ligatures if I remove the FRAC feature from the Wezterm config. This makes some sense as a trade-off, but I wanted to double check that there has to be such a trade-off. Ideally, I could enable FRAC *and* see those ligatures, which don't really look like fractions despite using a slash.

---

* Your font version: [28.0.1-dev-43f247f](https://github.com/AndydeCleyre/archbuilder_iosevka/releases/download/28.0.1-dev-43f247f/ttf-iosevka-term-custom-git-1703123013-1-any.pkg.tar.zst)
* Your font variant: Term
* Your operating system (name and version): Pop OS 22.04
* Your application using Iosevka: Wezterm

<details>
<summary>private-build-plans.toml</summary>

```toml
[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
exportGlyphNames = false
buildTextureFeature = true
spacing = "normal"

[buildPlans.IosevkaCustom.ligations]
inherits = "dlig"
# disables = []
# enables = []

# [buildPlans.IosevkaCustom.variants]
# inherits = "ss16"

[buildPlans.IosevkaCustom.variants.design]
digit-form = "old-style"
apl-form = "enable"
capital-a = "curly-serifless"
capital-b = "standard-interrupted-bilateral-serifed"
capital-c = "serifless"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifless"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "serifless"
capital-k = "curly-top-left-serifed"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-n = "standard-serifless"
capital-p = "closed-motion-serifed"
capital-q = "open-swash"
capital-r = "straight-open-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "straight-asymmetric-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifless-with-crossbar"
a = "double-storey-tailed"
b = "toothless-corner-serifless"
c = "serifless"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey-open"
h = "straight-serifless"
i = "hooky"
j = "serifless"
k = "curly-serifless"
l = "flat-tailed"
m = "short-leg-serifless"
n = "earless-corner-tailed-serifless"
p = "eared-motion-serifed"
q = "earless-corner-diagonal-tailed-serifless"
r = "corner-hooked-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "curly-serifless"
z = "straight-serifless-with-crossbar"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed-serifless"
lower-eth = "straight-bar"
lower-thorn = "serifed"
lower-alpha = "crossing"
capital-gamma = "bottom-serifed"
capital-delta = "curly"
lower-delta = "rounded"
lower-iota = "tailed-serifed"
capital-lambda = "curly-top-serifed"
lower-lambda = "tailed-turn"
lower-mu = "tailed-serifless"
lower-xi = "flat-top"
lower-pi = "tailed"
lower-tau = "flat-tailed"
lower-chi = "semi-chancery-straight"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-capital-ze = "unilateral-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "straight"
cyrl-em = "slanted-sides-hanging-serifed"
cyrl-en = "tailed-top-left-serifed"
cyrl-er = "earless-rounded-serifless"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
cyrl-ef = "cursive"
cyrl-che = "tailed"
cyrl-yeri = "round"
cyrl-yery = "round"
cyrl-capital-ya = "straight-motion-serifed"
cyrl-ya = "straight-tailed-motion-serifed"
zero = "diamond-unslashed"
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "oblique-arched"
six = "open-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "turn-hex-high"
underscore = "high"
caret = "high"
paren = "normal"
brace = "curly"
number-sign = "upright-tall"
ampersand = "flat-top"
at = "fourfold-solid-inner-tall"
dollar = "open-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
ascii-single-quote = "raised-comma"
ascii-grave = "straight"
question = "smooth"
pilcrow = "low"
cent = "open-cap"
partial-derivative = "curly-bar"
micro-sign = "toothed-serifless"
guillemet = "curly"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

# Override above variants for each slope:
# [buildPlans.IosevkaCustom.variants.upright]
# [buildPlans.IosevkaCustom.variants.italic]

[buildPlans.IosevkaCustom.weights.Regular]
shape = 600
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 800
menu = 700
css = 700

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

# [buildPlans.IosevkaCustom.slopes.Oblique]
# angle = 9.4
# shape = "oblique"
# menu  = "oblique"
# css   = "oblique"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.IosevkaTermCustom]
family = "Iosevka Term Custom"
exportGlyphNames = false
buildTextureFeature = true
spacing = "term"

[buildPlans.IosevkaTermCustom.ligations]
inherits = "dlig"
# disables = []
# enables = []

# [buildPlans.IosevkaTermCustom.variants]
# inherits = "ss16"

[buildPlans.IosevkaTermCustom.variants.design]
digit-form = "old-style"
apl-form = "enable"
capital-a = "curly-serifless"
capital-b = "standard-interrupted-bilateral-serifed"
capital-c = "serifless"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifless"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "serifless"
capital-k = "curly-top-left-serifed"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-n = "standard-serifless"
capital-p = "closed-motion-serifed"
capital-q = "open-swash"
capital-r = "straight-open-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "straight-asymmetric-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifless-with-crossbar"
a = "double-storey-tailed"
b = "toothless-corner-serifless"
c = "serifless"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey-open"
h = "straight-serifless"
i = "hooky"
j = "serifless"
k = "curly-serifless"
l = "flat-tailed"
m = "short-leg-serifless"
n = "earless-corner-tailed-serifless"
p = "eared-motion-serifed"
q = "earless-corner-diagonal-tailed-serifless"
r = "corner-hooked-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "curly-serifless"
z = "straight-serifless-with-crossbar"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed-serifless"
lower-eth = "straight-bar"
lower-thorn = "serifed"
lower-alpha = "crossing"
capital-gamma = "bottom-serifed"
capital-delta = "curly"
lower-delta = "rounded"
lower-iota = "tailed-serifed"
capital-lambda = "curly-top-serifed"
lower-lambda = "tailed-turn"
lower-mu = "tailed-serifless"
lower-xi = "flat-top"
lower-pi = "tailed"
lower-tau = "flat-tailed"
lower-chi = "semi-chancery-straight"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-capital-ze = "unilateral-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "straight"
cyrl-em = "slanted-sides-hanging-serifed"
cyrl-en = "tailed-top-left-serifed"
cyrl-er = "earless-rounded-serifless"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
cyrl-ef = "cursive"
cyrl-che = "tailed"
cyrl-yeri = "round"
cyrl-yery = "round"
cyrl-capital-ya = "straight-motion-serifed"
cyrl-ya = "straight-tailed-motion-serifed"
zero = "diamond-unslashed"
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "oblique-arched"
six = "open-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "turn-hex-high"
underscore = "high"
caret = "high"
paren = "normal"
brace = "curly"
number-sign = "upright-tall"
ampersand = "flat-top"
at = "fourfold-solid-inner-tall"
dollar = "open-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
ascii-single-quote = "raised-comma"
ascii-grave = "straight"
question = "smooth"
pilcrow = "low"
cent = "open-cap"
partial-derivative = "curly-bar"
micro-sign = "toothed-serifless"
guillemet = "curly"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

# Override above variants for each slope:
# [buildPlans.IosevkaTermCustom.variants.upright]
# [buildPlans.IosevkaTermCustom.variants.italic]

[buildPlans.IosevkaTermCustom.weights.Regular]
shape = 600
menu = 400
css = 400

[buildPlans.IosevkaTermCustom.weights.Bold]
shape = 800
menu = 700
css = 700

[buildPlans.IosevkaTermCustom.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

# [buildPlans.IosevkaTermCustom.slopes.Oblique]
# angle = 9.4
# shape = "oblique"
# menu  = "oblique"
# css   = "oblique"

[buildPlans.IosevkaTermCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.IosevkaFcmCustom]
family = "Iosevka FCM Custom"
exportGlyphNames = false
buildTextureFeature = true
spacing = "fontconfig-mono"

[buildPlans.IosevkaFcmCustom.ligations]
inherits = "dlig"
# disables = []
# enables = []

# [buildPlans.IosevkaFcmCustom.variants]
# inherits = "ss16"

[buildPlans.IosevkaFcmCustom.variants.design]
digit-form = "old-style"
apl-form = "enable"
capital-a = "curly-serifless"
capital-b = "standard-interrupted-bilateral-serifed"
capital-c = "serifless"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifless"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "serifless"
capital-k = "curly-top-left-serifed"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-n = "standard-serifless"
capital-p = "closed-motion-serifed"
capital-q = "open-swash"
capital-r = "straight-open-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "straight-asymmetric-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifless-with-crossbar"
a = "double-storey-tailed"
b = "toothless-corner-serifless"
c = "serifless"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey-open"
h = "straight-serifless"
i = "hooky"
j = "serifless"
k = "curly-serifless"
l = "flat-tailed"
m = "short-leg-serifless"
n = "earless-corner-tailed-serifless"
p = "eared-motion-serifed"
q = "earless-corner-diagonal-tailed-serifless"
r = "corner-hooked-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "curly-serifless"
z = "straight-serifless-with-crossbar"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed-serifless"
lower-eth = "straight-bar"
lower-thorn = "serifed"
lower-alpha = "crossing"
capital-gamma = "bottom-serifed"
capital-delta = "curly"
lower-delta = "rounded"
lower-iota = "tailed-serifed"
capital-lambda = "curly-top-serifed"
lower-lambda = "tailed-turn"
lower-mu = "tailed-serifless"
lower-xi = "flat-top"
lower-pi = "tailed"
lower-tau = "flat-tailed"
lower-chi = "semi-chancery-straight"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-capital-ze = "unilateral-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "straight"
cyrl-em = "slanted-sides-hanging-serifed"
cyrl-en = "tailed-top-left-serifed"
cyrl-er = "earless-rounded-serifless"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
cyrl-ef = "cursive"
cyrl-che = "tailed"
cyrl-yeri = "round"
cyrl-yery = "round"
cyrl-capital-ya = "straight-motion-serifed"
cyrl-ya = "straight-tailed-motion-serifed"
zero = "diamond-unslashed"
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "oblique-arched"
six = "open-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "turn-hex-high"
underscore = "high"
caret = "high"
paren = "normal"
brace = "curly"
number-sign = "upright-tall"
ampersand = "flat-top"
at = "fourfold-solid-inner-tall"
dollar = "open-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
ascii-single-quote = "raised-comma"
ascii-grave = "straight"
question = "smooth"
pilcrow = "low"
cent = "open-cap"
partial-derivative = "curly-bar"
micro-sign = "toothed-serifless"
guillemet = "curly"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

# Override above variants for each slope:
# [buildPlans.IosevkaFcmCustom.variants.upright]
# [buildPlans.IosevkaFcmCustom.variants.italic]

[buildPlans.IosevkaFcmCustom.weights.Regular]
shape = 600
menu = 400
css = 400

[buildPlans.IosevkaFcmCustom.weights.Bold]
shape = 800
menu = 700
css = 700

[buildPlans.IosevkaFcmCustom.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

# [buildPlans.IosevkaFcmCustom.slopes.Oblique]
# angle = 9.4
# shape = "oblique"
# menu  = "oblique"
# css   = "oblique"

[buildPlans.IosevkaFcmCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.IosevkaFixedCustom]
family = "Iosevka Fixed Custom"
exportGlyphNames = false
buildTextureFeature = true
spacing = "fixed"

[buildPlans.IosevkaFixedCustom.ligations]
inherits = "dlig"
# disables = []
# enables = []

# [buildPlans.IosevkaFixedCustom.variants]
# inherits = "ss16"

[buildPlans.IosevkaFixedCustom.variants.design]
digit-form = "old-style"
apl-form = "enable"
capital-a = "curly-serifless"
capital-b = "standard-interrupted-bilateral-serifed"
capital-c = "serifless"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifless"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "serifless"
capital-k = "curly-top-left-serifed"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-n = "standard-serifless"
capital-p = "closed-motion-serifed"
capital-q = "open-swash"
capital-r = "straight-open-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "straight-asymmetric-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifless-with-crossbar"
a = "double-storey-tailed"
b = "toothless-corner-serifless"
c = "serifless"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey-open"
h = "straight-serifless"
i = "hooky"
j = "serifless"
k = "curly-serifless"
l = "flat-tailed"
m = "short-leg-serifless"
n = "earless-corner-tailed-serifless"
p = "eared-motion-serifed"
q = "earless-corner-diagonal-tailed-serifless"
r = "corner-hooked-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "curly-serifless"
z = "straight-serifless-with-crossbar"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed-serifless"
lower-eth = "straight-bar"
lower-thorn = "serifed"
lower-alpha = "crossing"
capital-gamma = "bottom-serifed"
capital-delta = "curly"
lower-delta = "rounded"
lower-iota = "tailed-serifed"
capital-lambda = "curly-top-serifed"
lower-lambda = "tailed-turn"
lower-mu = "tailed-serifless"
lower-xi = "flat-top"
lower-pi = "tailed"
lower-tau = "flat-tailed"
lower-chi = "semi-chancery-straight"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-capital-ze = "unilateral-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "straight"
cyrl-em = "slanted-sides-hanging-serifed"
cyrl-en = "tailed-top-left-serifed"
cyrl-er = "earless-rounded-serifless"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
cyrl-ef = "cursive"
cyrl-che = "tailed"
cyrl-yeri = "round"
cyrl-yery = "round"
cyrl-capital-ya = "straight-motion-serifed"
cyrl-ya = "straight-tailed-motion-serifed"
zero = "diamond-unslashed"
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "oblique-arched"
six = "open-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "turn-hex-high"
underscore = "high"
caret = "high"
paren = "normal"
brace = "curly"
number-sign = "upright-tall"
ampersand = "flat-top"
at = "fourfold-solid-inner-tall"
dollar = "open-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
ascii-single-quote = "raised-comma"
ascii-grave = "straight"
question = "smooth"
pilcrow = "low"
cent = "open-cap"
partial-derivative = "curly-bar"
micro-sign = "toothed-serifless"
guillemet = "curly"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

# Override above variants for each slope:
# [buildPlans.IosevkaFixedCustom.variants.upright]
# [buildPlans.IosevkaFixedCustom.variants.italic]

[buildPlans.IosevkaFixedCustom.weights.Regular]
shape = 600
menu = 400
css = 400

[buildPlans.IosevkaFixedCustom.weights.Bold]
shape = 800
menu = 700
css = 700

[buildPlans.IosevkaFixedCustom.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

# [buildPlans.IosevkaFixedCustom.slopes.Oblique]
# angle = 9.4
# shape = "oblique"
# menu  = "oblique"
# css   = "oblique"

[buildPlans.IosevkaFixedCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.IosevkaQpCustom]
family = "Iosevka QP Custom"
exportGlyphNames = false
buildTextureFeature = true
spacing = "quasi-proportional"

[buildPlans.IosevkaQpCustom.ligations]
inherits = "dlig"
# disables = []
# enables = []

# [buildPlans.IosevkaQpCustom.variants]
# inherits = "ss16"

[buildPlans.IosevkaQpCustom.variants.design]
digit-form = "old-style"
apl-form = "enable"
capital-a = "curly-serifless"
capital-b = "standard-interrupted-bilateral-serifed"
capital-c = "serifless"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifless"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "serifless"
capital-k = "curly-top-left-serifed"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-n = "standard-serifless"
capital-p = "closed-motion-serifed"
capital-q = "open-swash"
capital-r = "straight-open-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "straight-asymmetric-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifless-with-crossbar"
a = "double-storey-tailed"
b = "toothless-corner-serifless"
c = "serifless"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey-open"
h = "straight-serifless"
i = "hooky"
j = "serifless"
k = "curly-serifless"
l = "flat-tailed"
m = "short-leg-serifless"
n = "earless-corner-tailed-serifless"
p = "eared-motion-serifed"
q = "earless-corner-diagonal-tailed-serifless"
r = "corner-hooked-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "curly-serifless"
z = "straight-serifless-with-crossbar"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed-serifless"
lower-eth = "straight-bar"
lower-thorn = "serifed"
lower-alpha = "crossing"
capital-gamma = "bottom-serifed"
capital-delta = "curly"
lower-delta = "rounded"
lower-iota = "tailed-serifed"
capital-lambda = "curly-top-serifed"
lower-lambda = "tailed-turn"
lower-mu = "tailed-serifless"
lower-xi = "flat-top"
lower-pi = "tailed"
lower-tau = "flat-tailed"
lower-chi = "semi-chancery-straight"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-capital-ze = "unilateral-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "straight"
cyrl-em = "slanted-sides-hanging-serifed"
cyrl-en = "tailed-top-left-serifed"
cyrl-er = "earless-rounded-serifless"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
cyrl-ef = "cursive"
cyrl-che = "tailed"
cyrl-yeri = "round"
cyrl-yery = "round"
cyrl-capital-ya = "straight-motion-serifed"
cyrl-ya = "straight-tailed-motion-serifed"
zero = "diamond-unslashed"
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "oblique-arched"
six = "open-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "turn-hex-high"
underscore = "high"
caret = "high"
paren = "normal"
brace = "curly"
number-sign = "upright-tall"
ampersand = "flat-top"
at = "fourfold-solid-inner-tall"
dollar = "open-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
ascii-single-quote = "raised-comma"
ascii-grave = "straight"
question = "smooth"
pilcrow = "low"
cent = "open-cap"
partial-derivative = "curly-bar"
micro-sign = "toothed-serifless"
guillemet = "curly"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

# Override above variants for each slope:
# [buildPlans.IosevkaQpCustom.variants.upright]
# [buildPlans.IosevkaQpCustom.variants.italic]

[buildPlans.IosevkaQpCustom.weights.Regular]
shape = 600
menu = 400
css = 400

[buildPlans.IosevkaQpCustom.weights.Bold]
shape = 800
menu = 700
css = 700

[buildPlans.IosevkaQpCustom.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

# [buildPlans.IosevkaQpCustom.slopes.Oblique]
# angle = 9.4
# shape = "oblique"
# menu  = "oblique"
# css   = "oblique"

[buildPlans.IosevkaQpCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

[buildPlans.IosevkaQpeCustom]
family = "Iosevka QPE Custom"
exportGlyphNames = false
buildTextureFeature = true
spacing = "quasi-proportional-extension-only"

[buildPlans.IosevkaQpeCustom.ligations]
inherits = "dlig"
# disables = []
# enables = []

# [buildPlans.IosevkaQpeCustom.variants]
# inherits = "ss16"

[buildPlans.IosevkaQpeCustom.variants.design]
digit-form = "old-style"
apl-form = "enable"
capital-a = "curly-serifless"
capital-b = "standard-interrupted-bilateral-serifed"
capital-c = "serifless"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifless"
capital-f = "top-left-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "serifless"
capital-k = "curly-top-left-serifed"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-n = "standard-serifless"
capital-p = "closed-motion-serifed"
capital-q = "open-swash"
capital-r = "straight-open-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "straight-asymmetric-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifless-with-crossbar"
a = "double-storey-tailed"
b = "toothless-corner-serifless"
c = "serifless"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey-open"
h = "straight-serifless"
i = "hooky"
j = "serifless"
k = "curly-serifless"
l = "flat-tailed"
m = "short-leg-serifless"
n = "earless-corner-tailed-serifless"
p = "eared-motion-serifed"
q = "earless-corner-diagonal-tailed-serifless"
r = "corner-hooked-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "curly-serifless"
w = "cursive-serifless"
x = "curly-serifless"
y = "curly-serifless"
z = "straight-serifless-with-crossbar"
long-s = "flat-hook-tailed"
eszet = "longs-s-lig-tailed-serifless"
lower-eth = "straight-bar"
lower-thorn = "serifed"
lower-alpha = "crossing"
capital-gamma = "bottom-serifed"
capital-delta = "curly"
lower-delta = "rounded"
lower-iota = "tailed-serifed"
capital-lambda = "curly-top-serifed"
lower-lambda = "tailed-turn"
lower-mu = "tailed-serifless"
lower-xi = "flat-top"
lower-pi = "tailed"
lower-tau = "flat-tailed"
lower-chi = "semi-chancery-straight"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-capital-ze = "unilateral-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "straight"
cyrl-em = "slanted-sides-hanging-serifed"
cyrl-en = "tailed-top-left-serifed"
cyrl-er = "earless-rounded-serifless"
cyrl-capital-u = "cursive-flat-hook-serifless"
cyrl-u = "cursive-flat-hook-serifless"
cyrl-ef = "cursive"
cyrl-che = "tailed"
cyrl-yeri = "round"
cyrl-yery = "round"
cyrl-capital-ya = "straight-motion-serifed"
cyrl-ya = "straight-tailed-motion-serifed"
zero = "diamond-unslashed"
one = "no-base"
two = "curly-neck"
three = "flat-top"
four = "semi-open"
five = "oblique-arched"
six = "open-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "straight-bar"
diacritic-dot = "round"
punctuation-dot = "round"
tilde = "low"
asterisk = "turn-hex-high"
underscore = "high"
caret = "high"
paren = "normal"
brace = "curly"
number-sign = "upright-tall"
ampersand = "flat-top"
at = "fourfold-solid-inner-tall"
dollar = "open-cap"
percent = "rings-segmented-slash"
bar = "natural-slope"
ascii-single-quote = "raised-comma"
ascii-grave = "straight"
question = "smooth"
pilcrow = "low"
cent = "open-cap"
partial-derivative = "curly-bar"
micro-sign = "toothed-serifless"
guillemet = "curly"
lig-ltgteq = "flat"
lig-neq = "slightly-slanted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

# Override above variants for each slope:
# [buildPlans.IosevkaQpeCustom.variants.upright]
# [buildPlans.IosevkaQpeCustom.variants.italic]

[buildPlans.IosevkaQpeCustom.weights.Regular]
shape = 600
menu = 400
css = 400

[buildPlans.IosevkaQpeCustom.weights.Bold]
shape = 800
menu = 700
css = 700

[buildPlans.IosevkaQpeCustom.slopes.Upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

# [buildPlans.IosevkaQpeCustom.slopes.Oblique]
# angle = 9.4
# shape = "oblique"
# menu  = "oblique"
# css   = "oblique"

[buildPlans.IosevkaQpeCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"
```

</details>
