### ISSUE TITLE
Website/Specimen: Add a scrollbar to Unicode map's dropdown menu.

### ISSUE THREAD

**Issue by jmcwilliams403** [be5invis/Iosevka#2194]
The map menu, or whatever it's called, goes offscreen on my 1080p monitor:
![image](https://github.com/be5invis/Iosevka/assets/37010132/497c128c-bf4f-4ea2-a606-dfe106e271ae)
It would be nice if it had its own scrollbar here:
![image](https://github.com/be5invis/Iosevka/assets/37010132/379a4041-bcd5-4aad-9171-25edf57959c5)

**Comment by akarzim** [comment]
Not sure if this is the better apporoach, but here is a try:

```css
#character-specimen #navigator-panel > .navigation-dropdown {
    max-height: 90vh;
}

#character-specimen #navigator-panel > .navigation-dropdown > .blocks-panel {
    overflow: auto;
}

#character-specimen #navigator-panel > .navigation-dropdown > .strips-panel {
    overflow: auto;
}
```

I can open a PR if this proposal sounds good to you :)
