### ISSUE TITLE
how to change width  and keep monospace

### ISSUE THREAD

**Issue by glepnir** [be5invis/Iosevka#2202]
**Is your feature request related to a problem? Please describe.**.

hello, great project. I thought I'd create in the discussion. . Because it deviates from a bug or feature request. But I see that the discussion is not enabled.
I'm a font noob. I don't really understand how fonts work. I definitely agree with you on designing Iosevka. Compact allows you to see more code. But for modern times larger monitors such as 4k 27inc are usually used. So the default Iosevka width looks too narrow. So I want to adjust the width appropriately. I usually use the Term font. Because I use tui for my daily work. Is changing the shape to 425 the right route? A simple build-plans example can be provided. Can my fork sync upstream changes or do I need to use private-build? Here is a reference for the fonts I use. Thank you again for your efforts. Have you not activated sponsor yet?

```
font_family      Iosevka Term Regular
bold_font        Iosevka Term Bold
italic_font      Iosevka Term Italic
bold_italic_font Iosevka Term Bold Italic
font_size 18
```

**Comment by glepnir** [comment]
thanks for kinda help. i tried this before. and i see some cusotm fonts of ioveska   also change xheight to 550 and leading to 1100 ? does this important ?

**Comment by glepnir** [comment]
I think i know how to change it thanks.

**Comment by glepnir** [comment]
Does this is correct ?
```toml
[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.widths.normal]
shape = 500
menu  = 5
css   = "normal"

[buildPlans.IosevkaCustom.weights.regular]
shape = 425
menu = 400
css = 400

[buildPlans.IosevkaCustom.metricOverride]
leading = 1100
xHeight = 550
```
