### ISSUE TITLE
450 weighth request

### ISSUE THREAD

**Issue by chmielcode** [be5invis/Iosevka#2410]
Fonts popular today are a little bit thicker. Would it be possible for you to add 450 font weight? Currently I  use CommitMono with 450 weight and it's almost perfect. Iosevka would be fantastic if I could install 450/450italic/bold/bolditalic set :)

**Comment by be5invis** [comment]
You can simply change the shape weight in your custom build plan.

**Comment by be5invis** [comment]
```toml
[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.IosevkaCustom.weights.Regular]
shape = 450 # HERE
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700
```
