### ISSUE TITLE
Build Process Gets Stuck at 557 Pending Tasks

### ISSUE THREAD

**Issue by kryzet** [be5invis/Iosevka#2584]
The build process gets stuck at 557 pending build tasks and keeps using the CPU and memory without any reported progress. 
![image](https://github.com/user-attachments/assets/0b7fd400-aa25-4322-a237-224f19d40e2b)

---
* Font version: [`9df636450d986d17c3dc3328bd4aa342214d45bf`](https://github.com/be5invis/Iosevka/tree/9df636450d986d17c3dc3328bd4aa342214d45bf)
* Font variant: Iosevka with `private-build-plans.toml`
* Operating system: Windows 11 x64 23H2
* Node.js version: 23.1.0
* `private-build-plans.toml`:
  ```toml
  [buildPlans.KryzetSIosevka]
  family = "Kryzet's Iosevka"
  spacing = "normal"
  serifs = "slab"
  noCvSs = false
  exportGlyphNames = true

    [buildPlans.KryzetSIosevka.ligations]
    inherits = "dlig"

  [buildPlans.KryzetSIosevka.widths.Condensed]
  shape = 500
  menu = 3
  css = "condensed"

  [buildPlans.KryzetSIosevka.widths.Normal]
  shape = 600
  menu = 5
  css = "normal"

  [buildPlans.KryzetSIosevka.widths.UltraCondensed]
  shape = 416
  menu = 1
  css = "ultra-condensed"

  [buildPlans.KryzetSIosevka.widths.ExtraCondensed]
  shape = 456
  menu = 2
  css = "extra-condensed"

  [buildPlans.KryzetSIosevka.widths.SemiCondensed]
  shape = 548
  menu = 4
  css = "semi-condensed"

  [buildPlans.KryzetSIosevka.widths.SemiExtended]
  shape = 658
  menu = 6
  css = "semi-expanded"

  [buildPlans.KryzetSIosevka.widths.Extended]
  shape = 720
  menu = 7
  css = "expanded"
  ```
* The detailed error log:
  ```
  Where do I get that?
  ```
