### ISSUE TITLE
two,straight-neck breaks build

### ISSUE THREAD

**Issue by ShalokShalom** [be5invis/Iosevka#2794]
Describe your problem here. Provide pictures and files if necessary.

---

* Your font version: git
* Your operating system (name and version): Linux
* Your application using Iosevka: VSCode

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 22.16.0 (LTS, Jod)

* Your `private-build-plans.toml`, if present:
  ```toml
  [buildPlans.Sharp]
  family = "Sharp"
  spacing = "normal"
  serifs = "sans"
  noCvSs = true
  exportGlyphNames = false
  noLigation = true
  
  [buildPlans.Sharp.variants]
  inherits = "ss10"

    [buildPlans.Sharp.variants.design]
    two = "straight-neck"
    three = "flat-top"
    four = "semi-open-non-crossing"
    zero = "unslashed"
    capital-g = "toothed-serifless-hooked"
    capital-i = "serifed"
    capital-j = "descending-flat-hook-serifless"
    capital-k = "symmetric-connected-serifed"
    capital-q = "straight"
    capital-r = "straight-open-motion-serifed"
    capital-s = "bilateral-inward-serifed"
    capital-u = "toothless-rounded-bilateral-motion-serifed"
    capital-v = "straight-motion-serifed"
    capital-w = "straight-vertical-sides-motion-serifed"
    f = "flat-hook-serifed"
    g = "single-storey-flat-hook-serifed"
    j = "flat-hook-serifed"
    k = "symmetric-connected-serifed"
    l = "serifed-flat-tailed"
    t = "flat-hook"
    u = "toothless-rounded"
    w = "cursive"
    x = "curly-serifless"
    y = "cursive-motion-serifed"
    z = "cursive"
    long-s = "flat-hook"
    eszet = "longs-s-lig-descending"
    lower-alpha = "tailed-barred"
    lower-xi = "rounded"
    cyrl-ka = "symmetric-touching-serifed"
    asterisk = "penta-low"
    paren = "flat-arc"
    number-sign = "slanted"
    ampersand = "upper-open"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    question = "corner-flat-hooked"
    pilcrow = "low"
    lig-ltgteq = "slanted"
    lig-neq = "more-slanted"
    lig-equal-chain = "without-notch"

  [buildPlans.Sharp.weights.Regular]
  shape = 400
  menu = 400
  css = 400
  
  [buildPlans.Sharp.weights.Light]
  shape = 300
  menu = 300
  css = 300
  
  [buildPlans.Sharp.weights.Medium]
  shape = 500
  menu = 500
  css = 500
  
  [buildPlans.Sharp.widths.Normal]
  shape = 500
  menu = 5
  css = "normal"
  
  [buildPlans.Sharp.widths.Condensed]
  shape = 416
  menu = 3
  css = "condensed"
  
  [buildPlans.Sharp.widths.SemiCondensed]
  shape = 456
  menu = 4
  css = "semi-condensed"
  ```

* The detailed error log:
```
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-CondensedLightItalic.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-SemiCondensedItalic.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-SemiCondensedLight.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-CondensedOblique.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-SemiCondensed.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-Light.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-CondensedLight.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-LightOblique.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-SemiCondensedLightOblique.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-Italic.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-LightItalic.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-CondensedLightOblique.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-CondensedItalic.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-Oblique.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-SemiCondensedOblique.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
× Error Unhandled exception when building "Builtin::File::dist/Sharp/TTF-Unhinted/Sharp-SemiCondensedLightItalic.ttf":
Error: Error: Composite {user} cannot be resolved: two,straight-neck.
at Composite.decompose (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:266:19)
at Composite.resolve (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:281:39)
at Module.apply (file:///home/shalok/Dokumente/Font/Iosevka/packages/param/src/variant.mjs:19:17)
at createParaImpl (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:32:15)
at paraT (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/param/index.mjs:42:16)
at main (file:///home/shalok/Dokumente/Font/Iosevka/packages/font/src/index.mjs:16:15)
at ChildProcess.<anonymous> (/home/shalok/Dokumente/Font/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
at ChildProcess.emit (node:events:518:28)
at emit (node:internal/child_process:949:14)
at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
  ```
