### ISSUE TITLE
Selectively override "slab"

### ISSUE THREAD

**Issue by emacsomancer** [be5invis/Iosevka#311]
It seems that "slab" overrides any other options. Is there any way to specify overrides to "slab" (for dotted zero, "l" styles etc.)?

(I suspect related to: https://github.com/be5invis/Iosevka/issues/176 )

**Comment by be5invis** [comment]
Write your config like this.

```toml
[buildPlans.iosevka-custom]
design = ["slab", "v-l-whatever"]
```
