### ISSUE TITLE
Possibility to set custom heights and leading in private build plans

### ISSUE THREAD

**Issue by glpub** [be5invis/Iosevka#385]
* Your font version: git
* Your font variant: any
* Your operating system (name and version): Arch Linux
* Your application using Iosevka: Any

I use custom values for xheight, cap, parenSize and leading variables to make font looks like this:
![screenshot](https://user-images.githubusercontent.com/23082740/70771202-2a32d480-1d68-11ea-9ee5-83ab7a83432a.png)

Setting the variables in parameters.toml seems weird to me, is that somehow possible to set them in private-build-plans.toml?

**Comment by alexeyten** [comment]
There is undocumented [private.toml](https://github.com/be5invis/Iosevka/blob/master/gen/generator.js#L20) config file.

I use it here https://github.com/be5invis/Iosevka/compare/dev...alexeyten:lynn-build

**Comment by glpub** [comment]
> There is undocumented private.toml config file.
>
> I use it here.

Perfect, exactly what I need, many thanks!

**Comment by wimstefan** [comment]
Thank you for that beautiful solution!
Is it also possible to define a different `slantAngle` for `s-italic` and `s-oblique`?
I've tried both 
```toml
[my-plan.s-italic]
slantAngle = 25
[my-plan.s-oblique]
slantAngle = 25
```
and 
```toml
[s-italic.my-plan]
slantAngle = 25
[s-oblique.my-plan]
slantAngle = 25
```
and couldn't succeed ...
