### ISSUE TITLE
Changing weights to 450 (normal) and 750 (bold) causes build to run out of memory

### ISSUE THREAD

**Issue by mrkgnao** [be5invis/Iosevka#422]
Using 400/700 (default) or 500/800 both work perfectly, but for some reason 450/750 causes build to get stuck at the last `node gen/generator` output.

**Comment by be5invis** [comment]
The build script does not support any weight other than `100`, `200`, ..., `900`. This is considered by-design (so far).

**Comment by be5invis** [comment]
A workaround is to modify the `parameters.toml` and add a `[w-450]` entry below it and blend the numbers.

**Comment by be5invis** [comment]
It now working. Demo:

```toml
[buildPlans.iosevka-mix]
family = "IosevkaMix"

[buildPlans.iosevka-mix.weights.regular]
shape = 450
menu  = 400
css   = 400

[buildPlans.iosevka-mix.weights.bold]
shape = 750
menu  = 700
css   = 700
```
