### ISSUE TITLE
Should there be a "Retina" or "Text" weight of Iosevka like Fira Code?

### ISSUE THREAD

**Issue by IceMan81** [be5invis/Iosevka#424]
While using FiraCode in my code editor (Intellij) on a Retina Mac, a number of times I've felt that it could be slightly thicker. In the past, I've compiled a slightly thicker version and used it, but I was never satisfied that I got the right thickness. Now a days I just download from "assets". Wondering if others have felt the need for a Text or Retina weight for Retina Macs? 

See the discussion here on why there is a Fira Code Retina
https://github.com/tonsky/FiraCode/issues/872

**Comment by IceMan81** [comment]
@be5invis What about 425 instead of 450 for Book weight? Is there some known convention for Book/Retina weights?

**Comment by be5invis** [comment]
@IceMan81 Mostly 450.
I'd like to keep "Book" only for custom build -- which means that it is not released by default, but you can configure it like this:

```toml
[buildPlans.iosevka-custom]            # <iosevka-custom> is your plan name
family = "Iosevka Custom"              # Font menu family name
design = ["common styles"]             # Common styles
upright = ["upright-only", "styles"]   # Upright-only styles
italic = ["italic-only", "styles"]     # Italic-only styles
oblique = ["oblique-only", "styles"]   # Oblique-only styles
hintParams = ["-a", "sss"]             # Optional custom parameters for ttfautohint

# Override default building weights
# When buildPlans.<plan name>.weights is absent
# All weights would built and mapped to default shape/CSS
# IMPORTANT : Currently "menu" property only support 100, 200, 300, 400, 450, 500, 600, 700, 800, 900.
#              and "shape" properly only supports number between 100 and 900 (inclusive).
[buildPlans.iosevka-custom.weights.regular]
shape = 400  # Weight for glyph shapes
menu  = 400  # Weight for menu name
css   = 400  # Weight for webfont CSS

[buildPlans.iosevka-custom.weights.book]
shape = 450
menu  = 450  # Use 450 here to name the font's weight "Book"
css   = 450

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu  = 700
css   = 700

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iosevka-custom.slants]
upright = "normal"
italic = "italic"
oblique = "oblique"
```
