### ISSUE TITLE
Iosevka Extended missing on IntelliJ

### ISSUE THREAD

**Issue by jmg-duarte** [be5invis/Iosevka#482]
* Your font version: 3.0.0-rc.6
* Your font variant: 01-iosevka & 03-iosevka-term (both hinted)
* Your operating system: Ubuntu 19.04 
* Your application using Iosevka: JetBrains IntelliJ 2019.3.4
---

I'm trying to use Iosevka Medium Extended in IntelliJ however I cannot select it.

![Screenshot from 2020-04-06 20-13-34](https://user-images.githubusercontent.com/15343819/78596138-26f5b400-7843-11ea-90c0-598f5d68c4c1.png)

In VSCode it works, no problems.

![Screenshot from 2020-04-06 20-14-47](https://user-images.githubusercontent.com/15343819/78596215-4ab8fa00-7843-11ea-8a1d-61a6cdb0df18.png)

![Screenshot from 2020-04-06 20-15-10](https://user-images.githubusercontent.com/15343819/78596244-599fac80-7843-11ea-83c6-15d1000220b6.png)

I tried installing them first in `~/.fonts`, then `~/.local/share/fonts` and finally `~/usr/share/fonts/truetype/iosevka`.
Always running `sudo fc-cache -v -f`and trying out again and again. 

Any ideas what the problem might be?

**Comment by AlsoScratch** [comment]
Probably consider making Normal and Extended different families? It would be easier to select.

**Comment by be5invis** [comment]
@AlsoScratch I will never do that. Modern font should use modern naming scheme, and it is _their respobsibility_ to make the font enumeration system work properly.
A workaround is to create two custom builds with different width mapping like this:

```toml
[buildPlans.iosevka-custom-normal]
family = "Iosevka Custom Normal"

[buildPlans.iosevka-custom-normal.widths.normal]
shape = 5
menu  = 5
css   = "normal"

##################################################

[buildPlans.iosevka-custom-wide]
family = "Iosevka Custom Wide"

[buildPlans.iosevka-custom-wide.widths.extended]
shape = 7
menu  = 5
css   = "normal"
```
