### ISSUE TITLE
Broken long ligature at beginning of line in macOS TextEdit

### ISSUE THREAD

**Issue by OceanS2000** [be5invis/Iosevka#548]
* Your font version: 3.0.1
* Your font variant: Iosevka Slab
* Your operating system (name and version): macOS 10.15.3
* Your application using Iosevka: TextEdit.app, TeXShop.app

---

Long ligatures as in `==>` are broken only at the line beginning of TextEdit.app. I noticed the issue when I use TeXShop.app to typeset some code in TeX. The TeX output has correct ligature, so it might be a bug in TextEdit.app?

<img width="662" alt="image" src="https://user-images.githubusercontent.com/30361859/82744629-c77d4480-9dad-11ea-8cb3-d5479df49e8c.png">

**Comment by be5invis** [comment]
Maybe related with how Apple intreprests reverse chaining lookup (which is used to extend the arrow bars for rightward arrows). Harfbuzz and DWrite worked well for them.

**Comment by be5invis** [comment]
@OceanS2000 Could you please test this build to see whether this version works? I reduced the complexity of that reverse sub so it may help.
[iosevka-reverse-sub-fix-apple-20200523-a.zip](https://github.com/be5invis/Iosevka/files/4672931/iosevka-reverse-sub-fix-apple-20200523-a.zip)

**Comment by akarzim** [comment]
Same here in Vim using iTerm (macOS):

<img width="462" alt="image" src="https://user-images.githubusercontent.com/130560/82749562-47a1ab00-9daa-11ea-82d8-1f0b55e7fe44.png">

---


- Your font version: 3.0.1
- Your font variant: Iosevka Custom
```toml
[buildPlans.iosevka-custom]   # <iosevka-custom> is your plan name
family = "Iosevka Custom"     # Font menu family name
design = ["leading-1250", "sp-term", "dlig", "cv08", "cv19", "cv67", "cv72", "cv74", "cv76", "cv78", "cv81", "cv83", "cv95"]   # Customize styles
upright = ["upright-only", "styles", "cv69", "cv79"]                 # Upright-only styles
italic = ["italic-only", "styles", "cv14", "cv24", "cv38", "cv92"]   # Italic-only styles
oblique = ["oblique-only", "styles", "cv69", "cv79"]                 # Oblique-only styles
hintParams = ["-a", "sss"]    # Optional custom parameters for ttfautohint
```
- Your operating system (name and version): macOS 10.15.4
- Your application using Iosevka: Vim, iTerm
