### ISSUE TITLE
How do I disable some ligatures?

### ISSUE THREAD

**Issue by xSke** [be5invis/Iosevka#552]
I'd like to build a font variant that contains the standard `calt` ligature set, *but without* equals sign ligatures. I can't figure out how to do that - the docs specify setting styles in the `.toml` file that add *more* ligatures or disable ligation entirely, but it doesn't specify how to remove individual ones. I'd also accept removing the default set entirely and then adding my own back individiually - but it doesn't seem like `no-ligation` works with adding specific ligatures afterwards.

Do let me know if I'm just missing something or misreading the docs...

**Comment by be5invis** [comment]
To build up a specific ligation set matches your need, you can configure like this:

```toml
[buildPlans.iosevka-custom]
design = ['calt-center-ops', 'calt-arrow', 'calt-html-comment', 'calt-trig', 'calt-llgg', 'calt-llggeq', 'calt-exeq', 'calt-plusplus', 'calt-kern-dotty']
......
```

When any `calt-####` exists, it will immediately clear the ligation set of `calt` feature and start building a new one using them. The definition lf `calt-####` style selectors could be seen in the README. (Styles for further customizing default (calt) ligation sets.)
