### ISSUE TITLE
No issue - just a big THANK YOU :)

### ISSUE THREAD

**Issue by wimstefan** [be5invis/Iosevka#576]
I'm so happy with how my font looks like at the moment and I realize that it's only possible with the tremendous cooperation and willingness to help from this amazing dev @be5invis !!!

This "issue" is just a little tribute and a BIG "Thank you" - you more than deserve that @be5invis 🙏

It took me some time to understand how I can use the customization possibilities but here's how my font looks like at the moment:
![iosevka-2020-06-02](https://user-images.githubusercontent.com/4605934/83520313-c64ec480-a4dd-11ea-8547-4aaa1cfec245.png)

And this is my private-build-plans.toml to achieve it:
```toml
[buildPlans.iosevka-customized]
family = "Iosevka Customized"
design = [
  "ligset-dlig",
  "v-f-straight-tailed",
  "v-g-singlestorey",
  "v-i-tailed",
  "v-j-straight",
  "v-k-straight",
  "v-l-tailed",
  "v-m-shortleg",
  "v-r-top-serifed",
  "v-eszet-traditional",
  "v-v-curly",
  "v-w-curly",
  "v-y-cursive",
  "v-capital-y-curly",
  "v-x-curly",
  "v-zero-reverse-slashed",
  "v-three-flattop",
  "v-seven-serifed",
  "v-nine-turned-six",
  "v-ampersand-flat-top",
  "v-tilde-high",
  "v-asterisk-high",
  "v-paragraph-high",
  "v-caret-high"
]
[buildPlans.iosevka-artesanal-tailed.widths.condensed]
shape = 3
menu  = 3
css   = "condensed"
[buildPlans.iosevka-artesanal-tailed.widths.normal]
shape = 5
menu  = 5
css   = "normal"
[buildPlans.iosevka-artesanal-tailed.widths.extended]
shape = 7
menu  = 7
css   = "expanded"
[buildPlans.iosevka-artesanal-tailed.weights.regular]
shape = 380
menu  = 400
css   = 400
[buildPlans.iosevka-artesanal-tailed.weights.medium]
shape = 480
menu  = 500
css   = 500
[buildPlans.iosevka-artesanal-tailed.weights.semibold]
shape = 580
menu  = 600
css   = 600
[buildPlans.iosevka-artesanal-tailed.weights.bold]
shape = 680
menu  = 700
css   = 700
[buildPlans.iosevka-artesanal-tailed.weights.extrabold]
shape = 780
menu  = 800
css   = 800
[buildPlans.iosevka-artesanal-tailed.weights.heavy]
shape = 880
menu  = 900
css   = 900
[buildPlans.iosevka-artesanal-tailed.slants]
upright = "normal"
italic = "italic"
```
