### ISSUE TITLE
How do you increase character width?

### ISSUE THREAD

**Issue by ejuarezg** [be5invis/Iosevka#592]
I'm building a wider font style and I wanted to know how you would go about increasing the character width.

The comments in the `[buildPlans.<plan name>.widths.normal]` section say the shape and menu values are **not** the actual character width.  So, how do you increase the character width?

**Comment by be5invis** [comment]
Well, the latest `dev` commits changed how the width customization work and now it uses actual real width of "char unit" (i.e., the width of most letters/numbers). So if you checkout latest `dev` you need to write things like this:

```toml
[buildPlans.<plan name>.widths.normal]
shape = 600
menu  = 5
css   = 'normal'
```
