### ISSUE TITLE
Do not build glyphs for excluded codepoints

### ISSUE THREAD

**Issue by alexeyten** [be5invis/Iosevka#607]
If I understand correctly, even with this config
```toml
[buildPlans.iosevka-custom.exclude-chars]
ranges = [[128, 1114111]]
```
build process generates all the glyphs and then remove excluded at the gc stage.

Is it possible not to build them at all, cause it is the most time consuming step?
