### ISSUE TITLE
Changing `sb` doesn't work

### ISSUE THREAD

**Issue by alexeyten** [be5invis/Iosevka#632]
Up until recently the configuration below worked fine and changed side bearing (`sb`).
But in commit bbf73e9748a1e756148ca2ea9abc365b68c30f10 the `postHives` was dropped so `buildPlan.lynn.post` does nothing.

Actually this affects `Iosevka Slab` as well, cause [this lines](https://github.com/be5invis/Iosevka/blob/master/params/parameters.toml#L71-L72) now has no effect.

---

* Your font version: git (dev branch)
* Your font variant: Custom
* Your operating system (name and version): Ubuntu 18.04

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 14
* Your _otfcc_ version: 0.10.4

* `private-build-plans.toml`:
```
[buildPlans.lynn]
family = 'Iosevka Lynn'
design = [
	'sp-term',
	'ss20',
	'lynn',
]
upright = [
	'v-i-hooky'
]
italic = [
	'v-k-curly'
]

[buildPlans.lynn.post]
design = [
	'lynn'
]
```

* `params/private-parameters.toml`
```
[lynn]
cap = 760
xheight = 560

[lynn.multiplies]
sb = 0.8
```

**Comment by be5invis** [comment]
Slab is a by design change.
I plan to move your request to `metricOverride` mechanism so you will no longer need to modify files under `params/`.

**Comment by be5invis** [comment]
Now you can use this config to override `cap`, `xheight` and `sb`.

```toml
[buildPlans.iosevka-lynn]
family = "Iosevka Lynn"
design = [
	'sp-term',
	'ss20',
	'lynn',
]
upright = [
	'v-i-hooky'
]
italic = [
	'v-k-curly'
]

[buildPlans.iosevka-lynn.metric-override]
cap = 760
xheight = 560

[buildPlans.iosevka-lynn.metric-override.multiplies]
sb = 0.8

```
