### ISSUE TITLE
[Q] Ligation for 3 equal sign, each of on top of another one.

### ISSUE THREAD

**Issue by dehghani-mehdi** [be5invis/Iosevka#713]
Is there any chance to have it?

**Comment by be5invis** [comment]
Could you have images about that?

**Comment by dehghani-mehdi** [comment]
Something like FiraCode's one:

![eq](https://user-images.githubusercontent.com/9152330/98070886-460b0180-1e77-11eb-8684-cdcf65197512.png)

**Comment by be5invis** [comment]
This is not enabled for default `calt` **on purpose**, since it is designed to be generic and not too focusing on certain language. To use, choose `CLIK` feature tag.

**Comment by dehghani-mehdi** [comment]
Thank you for your great support @be5invis and great font of course.

I'm sorry but I didn't get what you mean by _choose CLIK feature tag_ I have to build the font by myself?

**Comment by be5invis** [comment]
@dehghani-mehdi Depends on the software you use.

* If you are using it with CSS, use `font-feature-settings: 'calt' 0, 'CLIK' 1`
* In software supports custom features like VSCode, you could configure it to use `CLIK`. For example in VSCode you use `{"editor.fontLigatures": "'calt' 0, 'CLIK' 1"}`.
* Otherwise, you need to create a custom build.

**Comment by dehghani-mehdi** [comment]
I'm using Visual Studio and as far as I know there is no way to specify that option in VS. so I have to go with hard option, the custom build.

If I follow build instruction and use the config file which you [mentioned in README](https://github.com/be5invis/Iosevka#build-your-own-style) and change `featureTag` to `CLIK`, is that enough? _right now I use `Envy Code R Style` btw_

**Comment by be5invis** [comment]
@dehghani-mehdi 

For V3 you could configure like this:

```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
design = ["ss10", "ligset-clike"]
```

Note that the in-development V4's config format **will become significantly different**. It is not finalized yet but will highly likely look like this:

```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
[buildPlans.iosevka-custom.variants]
inherits = "ss10"
[buildPlans.iosevka-custom.ligations]
inherits = "clike"
```
