### ISSUE TITLE
Different digit-form's for upright/oblique/italic

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#724]
Is it possible to apply different `digit-form`s (`lining`/`old-style`) to different styles (`upright`/`oblique`/`italic`)?

In iosevka 3.x it was possible by using something like
```toml
[buildPlans.iosevka-x]
design = []
upright = ["default-to-lining-figures"]
oblique = ["default-to-lining-figures"]
italic = ["default-to-old-style-figures"]
```

**Comment by be5invis** [comment]
Moved digit form into variant selector, so now you could set digit form like this:

```toml
[buildPlans.iosevka-custom.variants.upright]
digit-form = "lining"

[buildPlans.iosevka-custom.variants.italic]
digit-form = "old-style"
```

Closing.
