### ISSUE TITLE
npm build.sh script should include what?

### ISSUE THREAD

**Issue by kanaanayt** [be5invis/Iosevka#735]
I haven't used nodejs or npm before. So I'm not sure what goes into the build script section. I'm trying to build a customized font from source.

I've just initialized using npm init. So I don't have any scripts. I just need a build script apparently. But every online source does it in a different way.

Thanks

**Comment by be5invis** [comment]
I think you need to clone this repo and in your script, the procedures is like:

 * Populate some data into `private-build-plans.toml`. Note that since v4.0-alpha.1 its syntax **has been changed and is not compatible with any earlier version**.
 * Then run `npm run build -- ttf::<your plan name>`.

**Comment by kanaanayt** [comment]
After cloning the repo and following the build instructions I get the following error:
Error: Error: Cannot find module '../glyphs/index'
Require stack:
- /Users/kanaanabukhadra/fonts/Iosevka/font-src/gen/build-font.js
- /Users/kanaanabukhadra/fonts/Iosevka/font-src/index.js
- /Users/kanaanabukhadra/fonts/Iosevka/node_modules/verda/lib/actions/nodejs/nodejs-call-process.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/kanaanabukhadra/fonts/Iosevka/font-src/gen/build-font.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kanaanabukhadra/fonts/Iosevka/font-src/gen/build-font.js',
    '/Users/kanaanabukhadra/fonts/Iosevka/font-src/index.js',
    '/Users/kanaanabukhadra/fonts/Iosevka/node_modules/verda/lib/actions/nodejs/nodejs-call-process.js'
  ]
}
    at ChildProcess.<anonymous> (/Users/kanaanabukhadra/fonts/Iosevka/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by be5invis** [comment]
@kanaanayt I think the problem you saw is the same as #738. `dev` fixed that.

**Comment by kanaanayt** [comment]
Alright it works. Is it possible to build a custom extended with width 350 (not 300 or 400, but in between)
The following doesn't seem to work.

[buildPlans.iosevka-custom.weights.extended]
shape = 340  # Weight for glyph shapes.
menu  = 340  # Weight for the font's names.
css   = 340  # Weight for webfont CSS.

**Comment by wimstefan** [comment]
You're modifying the *weights* and not the *widths* ...

I recommend having a look at the brand new Customizer -> https://typeof.net/Iosevka/customizer
It helps you to find the values you want to use ... even with preview :)

**Comment by be5invis** [comment]
@kanaanayt Could you please clarify what you want to change: weight (stroke thickness) or width (letter wide-ness)? `350` looks very like a weight.

The config may look like this, which will make the strokes thinner but the OS / software will still think it is "regular".

```toml
[buildPlans.iosevka-custom.weights.regular]
shape = 350 # Weight for glyph shapes.
menu  = 400 # Weight for the font's names.
css   = 400 # Weight for webfont CSS.
```

**Comment by kanaanayt** [comment]
I'm trying to build a custom extended font with a weight of 350. Iosevka Fixed SS14 Extended, with 350, not 300 or 400. What should private-build-plans contain in order to accomplish that?

**Comment by be5invis** [comment]
If you need both normal width and extended width being built, and the OS recognizes wider variant as "Extended" subfamily:

```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-custom.variants]
inherits = "ss14"

[buildPlans.iosevka-custom.weights.regular]
shape = 350 # This line is changed
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700
```

If you want the extended width only and force the OS to think it is normal:

```toml
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-custom.variants]
inherits = "ss14"

[buildPlans.iosevka-custom.widths.normal]
shape = 576
menu = 5
css = "normal"

[buildPlans.iosevka-custom.weights.regular]
shape = 350 # This line is changed
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700
```
