### ISSUE TITLE
enabling the ligation does not work

### ISSUE THREAD

**Issue by akarzim** [be5invis/Iosevka#744]
It seems that I am no longer able to enable the ligation since the new syntax of the custom plan 4.0.

In the following example, I've activated these ligations:
- `eqeqeq`: Enable special ligation for `===` with triple lines.
- `exeq-alt-1`: Enable ligation for `!=` and `!==` with a dot at below for distinction.

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/130560/99877910-c6fd2380-2c01-11eb-8332-3481a1289022.png">

---

* Your font version: 4.0.0-beta.3
* Your font variant: custom plan
* Your operating system (name and version): macOS Big Sur 11.0.1
* Your application using Iosevka: iTerm, Firefox, FontForge

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: 15.2.0
* Your `private-build-plans.toml`, if present:

```toml
[buildPlans.iosevka-test]
family = "Iosevka Test"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-test.ligations]
enables  = ["eqeqeq", "exeq-alt-1"]
```
