### ISSUE TITLE
Missing ligation for !== with a dot below

### ISSUE THREAD

**Issue by akarzim** [be5invis/Iosevka#748]
Either the description of `exeq-alt-1` is incorrect or the ligation does not behave as expected. 

<img width="764" alt="image" src="https://user-images.githubusercontent.com/130560/99887071-989f3880-2c41-11eb-91f2-ab720bfb9b00.png">

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/130560/99887119-d3a16c00-2c41-11eb-833d-a0fa785f9a8c.png">

Perhaps a complementary `exeqeq-alt-1` ligation would do the trick?

---

- Your font version: 4.0.0-beta.3
- Your font variant: custom plan
- Your operating system (name and version): macOS Big Sur 11.0.1
- Your application using Iosevka: iTerm, Firefox, FontForge

If you have problem when building Iosevka, please provide these information:

- Your Node.js version: 15.2.0
- Your private-build-plans.toml, if present:

```toml
[buildPlans.iosevka-test]
family = "Iosevka Test"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-test.ligations]
enables  = ["eqeqeq", "exeq-alt-1"]
```

**Comment by be5invis** [comment]
It looks like that FontForge's feature interpreter has bugs? This is what supposed to happen with your config:
![image](https://user-images.githubusercontent.com/240091/99887463-771a5e80-2bf9-11eb-96cf-3268755d5d77.png)
Alternatives for triple-line and other exclamation-related ligations are added.

**Comment by akarzim** [comment]
My bad! The screenshot I published was based on this configuration: `enables = ["eqeqeq", "exeqeq", "exeq-alt-1"]`.

It works like a charm with the new ligations you just added:

```toml
[buildPlans.iosevka-custom.ligations]
enables  = ["eqeqeq", "exeqeq-alt-1", "exeq-alt-1"]
```

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/130560/99898982-214fc000-2ca6-11eb-86a8-1c547b62d614.png">

Since version 4.0.0 allows us breaking changes, perhaps "exeq-dotted" or "exeq-exclam" would be more explicit?
