### ISSUE TITLE
[Variant Request] Dotted and slashed rounded 0 variants

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#834]
- [x] The requested variant shape does not go too far away from Iosevka's design.
- [x] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [x] Some other monospace/programming fonts supported the requested variant. Provide images below.

------

In #828 a rounded 0 variant was added though only for the unslashed 0. For consistency, I suggest adding dotted and slashed variants for this shape of 0 too.

**Comment by NoxUltima** [comment]
Tried both `zero = 'slashed-oval'` and `zero = 'reverse-slashed-oval'` and it **still** has the basic oval shape without the slashes. Will update you once I have tried the rest out. Anyway thanks for adding :) 

My TOML config file

```toml
[buildPlans.ionix]
family = "Ionix"
spacing = "normal"
serifs = "sans"
desc = "Monospaced"
snapshotFamily = "ionix"
no-cv-ss = true

[buildPlans.ionix.variants]
inherits = "ss15"

[buildPlans.ionix.variants.design]
capital-a = "straight-motion-serifed"
capital-b = "more-asymmetric-unilateral-motion-serifed"
capital-d = "more-rounded-unilateral-motion-serifed"
capital-e = "motion-serifed"
capital-f = "motion-serifed"
capital-g = "toothless-rounded-capped"
capital-h = "motion-serifed"
capital-i = "serifed"
capital-j = "serifed-both-sides"
capital-k = "symmetric-disconnected-motion-serifed"
capital-l = "motion-serifed"
capital-m = "flat-bottom-motion-serifed"
capital-n = "motion-serifed"
capital-p = "open-motion-serifed"
capital-q = "detached-horizontal-tailed"
capital-r = "straight-open-motion-serifed"
capital-t = "motion-serifed"
capital-s = "serifed"
capital-u = "motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-double-v-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-motion-serifed"
capital-z = "top-motion-serifed"
a = "double-storey-motion-serifed"
b = "toothless-corner-motion-serifed"
d = "toothed-motion-serifed"
e = "flat-crossbar"
f = "flat-hook-serifed"
g = "double-storey-open"
h = "straight-motion-serifed"
i = "serifed-asymmetric"
j = "flat-hook-serifed"
k = "symmetric-disconnected-motion-serifed"
l = "zshaped"
m = "motion-serifed"
n = "straight-motion-serifed"
p = "motion-serifed"
q = "earless-corner-tailed"
r = "compact-serifed"
s = "serifed"
t = "flat-hook-short-neck2"
u = "toothless-corner-motion-serifed"
v = "straight-motion-serifed"
w = "straight-asymmetric-motion-serifed"
x = "straight-motion-serifed"
y = "straight-turn-motion-serifed"
z = "motion-serifed"
eszet = "traditional"
turn-v = "straight"
lambda = "straight"
cyrl-capital-u = "straight"
zero = "reverse-slashed"
one = "base-flat-top-serif"
two = "curly-neck"
three = "flattop"
four = "semi-open-non-crossing"
five = "oblique-upper-left-bar"
six = "closed-contour"
seven = "crossbar-serifed"
eight = "crossing"
nine = "straight-bar"
tilde = "low"
asterisk = "hexlow"
underscore = "above-baseline"
paragraph-sign = "high"
caret = "low"
paren = "large-contour"
brace = "curly"
number-sign = "upright-open"
ampersand = "upper-open"
at = "threefold"
dollar = "throughcap"
percent = "dots"
bar = "force-upright"
lig-ltgteq = "slanted"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "corner"
```
