### ISSUE TITLE
Serifs for slab cyrl/Ze

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#843]
Current version of cyrillic `Ze` (uppercase U+0417 and lowercase U+0437) doesn't have serifs under `slab` style. It would be great to have ones like other similar glyphs do.

![image](https://user-images.githubusercontent.com/2502094/105960049-c1064180-608d-11eb-9338-650d724c830c.png)

**Comment by be5invis** [comment]
Should follow `C` / `c`

**Comment by pv4** [comment]
Either so, or just always add the serif if building `slab` (the same applies for `Э` though). There are many other cyrillic glyphs anyway that have serifs in `slab` independently of `C` shape.

**Comment by pv4** [comment]
Following C/c would be great if it's set in variants.toml so that a user can override the variant wanted by hand if they want. Like it's done for `cyrl/te.italic`:

```toml
[prime.m.variants.normal]
rank = 1
description = "`m` with normal middle leg, touching the baseline"
selector.m = "normal"
selector."cyrl/te.italic" = "normal"
```

I think it's a better long-term solution (and the best among of what I can imagine now).
