### ISSUE TITLE
Stylistic sets for Recursive Mono and PT Mono 

### ISSUE THREAD

**Issue by NoxUltima** [be5invis/Iosevka#855]
So I thought from the current set of Iosevka variants, two new stylistic sets inspired by two different programming fonts. 

It would be cool to have Iosevka with a Recursive Mono flavour (especially the uppercase U and the motion-serifed BDEFPR), as well as PT Mono "littered" with motion serifs.

Lowercase v, w, x and z are to be substituted with `curly` variants to try to match the cursive/handwriting style of #852. 
```toml
v = 'curly-motion-serifed'
w = 'curly'
x = 'curly'
z = 'curly-top-motion-serifed'
```

Recursive Mono
![Recursive Mono](https://user-images.githubusercontent.com/16898444/106354209-faa7a880-632a-11eb-8128-41d19d37764a.png)

PT Mono
![PT Mono](https://user-images.githubusercontent.com/16898444/106354206-f3809a80-632a-11eb-80b2-4f9027b66d32.png)
