### ISSUE TITLE
Iosevka Sparkle

### ISSUE THREAD

**Issue by dixius99** [be5invis/Iosevka#859]
Just curious about the decision to remove Iosevka Sparkle in the new 5.0 versions. I really liked it, though I think Aile and Etoile are also both nice.

**Comment by be5invis** [comment]
Because now quasi-proportionals support customization, then keeping a separate family is not necessary. (Actually, I even want to rename Etoile to Aile Slab...)

**Comment by be5invis** [comment]
Closing as by design.

**Comment by dixius99** [comment]
Oh, I see. Thanks.

**Comment by flakyhermit** [comment]
@be5invis I see, but why aren't customized versions of quasi-proportionals not available in 'Releases'? Do I have to compile it myself? Also, which settings make the font look exactly like Sparkle?

**Comment by be5invis** [comment]
@flakyhermit This was the config used in v4, should be able to recreate Sparkle:

```toml
[buildPlans.iosevka-sparkle]	
family  = "Iosevka Sparkle"	
desc = "Hybrid, like iA Writer’s Duo"	
spacing = "quasi-proportional"	
no-cv-ss = true	
no-ligation = true	
snapshotFamily = 'iosevka-sparkle'	

[buildPlans.iosevka-sparkle.variants.design]	
at = 'fourfold'	
j = 'flat-hook-serifed'	

[buildPlans.iosevka-sparkle.variants.upright]	
i = 'serifed'	
l = 'serifed'	
f = 'serifed'	
r = 'serifed'	

[buildPlans.iosevka-sparkle.variants.oblique]	
i = 'serifed'	
l = 'serifed'	
f = 'serifed'	
r = 'serifed'	

[buildPlans.iosevka-sparkle.variants.italic]	
i = 'serifed-tailed'	
l = 'serifed-tailed'	
f = 'flat-hook-tailed'	
r = 'top-serifed'	

# Letterform control for U+1D670 ... U+1D6A3	
[buildPlans.iosevka-sparkle.derivingVariants.mathtt.design]	
at = 'threefold'	
j = 'flat-hook-serifed'	

[buildPlans.iosevka-sparkle.derivingVariants.mathtt.upright]	
i = 'serifed'	
l = 'serifed'	
f = 'serifed'	
r = 'serifed'	

[buildPlans.iosevka-sparkle.derivingVariants.mathtt.oblique]	
i = 'serifed'	
l = 'serifed'	
f = 'serifed'	
r = 'serifed'	

[buildPlans.iosevka-sparkle.derivingVariants.mathtt.italic]	
i = 'serifed-tailed'	
l = 'serifed-tailed'	
f = 'flat-hook-tailed'	
r = 'top-serifed'	

[buildPlans.iosevka-sparkle.widths.normal]	
shape = 576	
menu  = 5	
css   = "normal"	
```
