### ISSUE TITLE
Powerline glyphs at fontsize > 12

### ISSUE THREAD

**Issue by robertgzr** [be5invis/Iosevka#86]
I don't know if this is only related to my setup or if it's a general issue but I can' get the powerline glyphs to look right at fontsize 13

vimr:
![](http://i.imgur.com/PuPURu2.png)
![](http://i.imgur.com/r8WlnMW.png)
iterm2:
![](http://i.imgur.com/su9D376.png)

**Comment by be5invis** [comment]
Are you setting the line height correctly?
Powerline glyphs are extremely sensitive. The default line height is 1.25em, I think it is rounding error.

**Comment by be5invis** [comment]
I've added four parameters in `parameters.toml`:
```toml
# Powerline-specific parameters
powerlineScaleY = 1 # Vertical scale
powerlineScaleX = 1 # Horizontal scale
powerlineShiftY = 0 # Vertical shift. Unit: 1/1000em
powerlineShiftX = 0 # Horizontal shift. Unit: 1/1000em
```
You can adjust these values to make Powerline glyphs larger, or move them to the best position.

**Comment by robertgzr** [comment]
That works perfectly for `U+E0B0` and `U+E0B2` but it seems to break the other two.
![](http://i.imgur.com/rq8Advc.png)

I only changed the powerline section:
```toml
# Powerline-specific parameters
powerlineScaleY = 1.2 # Vertical scale
powerlineScaleX = 1 # Horizontal scale
powerlineShiftY = 0 # Vertical shift
powerlineShiftX = 0 # Horizontal shift
```
