### ISSUE TITLE
Lower case italic x more like in IBM Plex Mono

### ISSUE THREAD

**Issue by faustocintra** [be5invis/Iosevka#917]
- [X] The requested variant shape does not go too far away from Iosevka's design.
- [X] The requested variant does not conflict with any characters in Unicode that Iosevka currently supports.
- [ ] At least two monospace/programming fonts, created by different designers, supported the requested variant. Provide images below.

------

I'm very glad to see cursive x variant introduced in 5.0.6, but I expected it was more like IBM Plex Mono italic style. See image for reference. The side hooks in IBM Plex Mono seem more open.

![x](https://user-images.githubusercontent.com/18018239/111619472-630bf580-87c4-11eb-8e51-dfea3793b282.png)

**Comment by pv4** [comment]
May be something like the one on the picture (but not so ugly since it's made in gimp with "circle" tool)? The picture is for `heavy` weight since it's the bottleneck for the current cursive `x` variant (the current variant has thinner stems than the most glyphs).

![image](https://user-images.githubusercontent.com/2502094/111664932-31b61880-880a-11eb-997f-dddbcaafe3bf.png)

**Comment by akarzim** [comment]
Or maybe something more asymetric, based on the diagonal tail variant of `i`, `j`, or `l` characters :

<img width="225" alt="x" src="https://user-images.githubusercontent.com/130560/111671902-ae9cbe80-8819-11eb-9101-af2c38086577.png">

**Comment by pv4** [comment]
One more variant with "more square" figure. What I mean is making the edges similar to the top tail of `f` or the bottom tail of `t`.

@be5invis these're not final variants, and they should be probably thought about for some time. The variants are just sketches pointing the direction toward the "Iosevka style" cursive `x` as it's seen by me.

![image](https://user-images.githubusercontent.com/2502094/111691114-deea5a00-8825-11eb-8b0b-549cade02379.png)

**Comment by be5invis** [comment]
@pv4 Your shape should be considered as a new variant, instead of "cursive".
@akarzim's should work better.

**Comment by faustocintra** [comment]
@akarzim did was more meaningful than I supposed to be. In order to better match IBM Plex Mono italics, the hooks should be asymetric, with the more angled ones mimicking the style of `i`, `j`, `l` or `t` from the reference typeface.

Thanks for finding the words I coundn't.

**Comment by be5invis** [comment]
Refined geometry of cursive `x`.

![image](https://user-images.githubusercontent.com/240091/111730948-af404f80-882f-11eb-8e4f-35f8bb700dfc.png)

**Comment by wimstefan** [comment]
Thanks for looking into this @be5invis !

But on my system the 'x' looks still a bit "squeezed" compared to the IBM Plex Mono glyph ...

1. Iosevka
![iosevka-x](https://user-images.githubusercontent.com/4605934/111782898-dcd1db00-88b9-11eb-8d05-6abd8a1cb5b3.png)

2. IBM Plex Mono Italic
![ibm-plex-mono-x](https://user-images.githubusercontent.com/4605934/111782896-dc394480-88b9-11eb-949f-850775e07747.png)

**Comment by be5invis** [comment]
@wimstefan Well it is because Iosevka itself is narrower. Extended should match the width better I think.

**Comment by wimstefan** [comment]
> @wimstefan Well it is because Iosevka itself is narrower. Extended should match the width better I think.

@be5invis thanks for the swift response! I couldn't come back earlier since RL caught me :-/
In that case I'll stick with the default width since I like that very much with all the other characters. 

Thanks for this fantastic font! I'm using it literally everywhere - even on my phone ;-)

**Comment by pv4** [comment]
> I'm using it literally everywhere - even on my phone ;-)

Same here :) But only on desktop. When I have time to investigate how to use it on my phone, I'll definitely try doing it.

**Comment by wimstefan** [comment]
If you're running Magisk on your phone I can provide you with a installable zip file ... you'd have to do it with my customizations though 😏
Here's how it looks like: 
![Screenshot_20210322-210414.png](https://user-images.githubusercontent.com/4605934/112052765-c8107400-8b53-11eb-9e20-764e256ef10c.png)

**Comment by pv4** [comment]
> If you're running Magisk on your phone I can provide you with a installable zip file

Thanks, but I'll try to do it myself :) Besides, I'm not a mobile expert so I don't use root. I hope I will be able to create a custom theme or install a custom font some other non-root way.

> Here's how it looks like:

Nice :) Looks like you use most of the features appeared in Iosevka recently.

**Comment by faustocintra** [comment]
@wimstefan, would you please share your `private-build-plans.toml` file? Your customizations look quite interesting.

**Comment by wimstefan** [comment]
> > If you're running Magisk on your phone I can provide you with a installable zip file
> 
> Thanks, but I'll try to do it myself :) Besides, I'm not a mobile expert so I don't use root. I hope I will be able to create a custom theme or install a custom font some other non-root way.

Sure. Let me know if you change your mind :)

> > Here's how it looks like:
> 
> Nice :) Looks like you use most of the features appeared in Iosevka recently.
> On your screenshot Iosevka doesn't even look like a monospace font for programmers. It looks like a usual but beautiful font.
>
Thank you! I'm quite happy that the font looks balanced enough for both terminal and desktop ... and I'm surprised that I don't get bored when using it for everything. Quite the contrary is the case 😏

**Comment by wimstefan** [comment]
> @wimstefan, would you please share your `private-build-plans.toml` file? Your customizations look quite interesting.
> 

Sure. Here we go ...

``` toml
[buildPlans.iosevka-artesanal]
family = "Iosevka Artesanal"
serifs = "sans"
no-cv-ss = "true"
onumZeroHeightRatio = "1"
[buildPlans.iosevka-artesanal.variants.design]
capital-a = "curly-motion-serifed"
capital-b = "standard-interrupted-bilateral-motion-serifed"
capital-d = "more-rounded-unilateral-motion-serifed"
capital-e = "motion-serifed"
capital-f = "motion-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "motion-serifed"
capital-i = "short-serifed"
capital-j = "serifed-symmetric"
capital-k = "curly-motion-serifed"
capital-l = "motion-serifed"
capital-m = "hanging-motion-serifed"
capital-n = "asymmetric-motion-serifed"
capital-p = "open-motion-serifed"
capital-r = "curly-open-motion-serifed"
capital-s = "bilateral-serifed"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "curly-motion-serifed"
capital-x = "curly-motion-serifed"
capital-y = "curly-motion-serifed"
# capital-z = "curly-motion-serifed"
capital-z = "curly-with-horizontal-crossbar"
a = "double-storey-toothless-corner"
b = "toothless-corner-motion-serifed"
d = "toothless-corner-motion-serifed"
e = "rounded"
f = "diagonal-tailed-crossbar-at-x-height"
g = "single-storey-earless-corner-flat-hook"
h = "straight"
i = "diagonal-tailed"
j = "diagonal-tailed-serifless"
k = "curly-motion-serifed"
l = "diagonal-tailed"
m = "earless-single-arch-short-leg"
n = "earless-corner-straight"
r = "serifless"
s = "bilateral-serifed"
t = "diagonal-tailed"
u = "toothless-corner"
v = "cursive-serifed"
w = "curly"
x = "curly-motion-serifed"
y = "cursive-flat-hook"
z = "cursive-with-horizontal-crossbar"
eszet = "traditional"
digit-form = "old-style"
zero = "reverse-slashed-oval"
one = "nobase-long-top-serif"
two = "straight-neck"
three = "flattop"
four = "semi-open"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "bend-crossbar"
nine = "open-contour"
ampersand = "flat-top"
asterisk = "high"
at = "short"
bar = "force-upright"
caret = "high"
dollar = "interrupted-cap"
number-sign = "slanted-open"
paragraph-sign = "high"
tilde = "high"
[buildPlans.iosevka-artesanal.metric-override]
leading = 1150
parenSize = 1100 # 966 is default
[buildPlans.iosevka-artesanal.ligations]
inherits = "default-calt"
[buildPlans.iosevka-artesanal.widths.normal]
shape = 500
menu  = 5
css   = "normal"
[buildPlans.iosevka-artesanal.weights.regular]
shape = 400
menu  = 400
css   = 400
[buildPlans.iosevka-artesanal.weights.semibold]
shape = 600
menu  = 600
css   = 600
[buildPlans.iosevka-artesanal.weights.bold]
shape = 660
menu  = 700
css   = 700
[buildPlans.iosevka-artesanal.weights.extrabold]
shape = 800
menu  = 800
css   = 800
[buildPlans.iosevka-artesanal.weights.heavy]
shape = 900
menu  = 900
css   = 900
[buildPlans.iosevka-artesanal.slopes]
upright = "normal"
italic = "italic"
```

I hope it's OK that I'm posting the configuration directly ... please let me know if you prefer an attached file instead.
