### ISSUE TITLE
Extended subfamily width 0.6em vs 0.576em?

### ISSUE THREAD

**Issue by pv4** [be5invis/Iosevka#943]
Commit 584e7a7fe00037190ecfc553f9563574d84a7aa1 ("The grades for width is updated to make the unit width of Extended subfamily being 0.6em.") replaces 576 by 600 for `aile`/`etoile` leaving 576 for `Iosevka Extended` itself.

`build-plans.toml`:
```toml
[widths.extended]
shape = 576
menu  = 7
css   = "expanded"
```

Is this expected? Sorry for the noise.
