### ISSUE TITLE
Can't build Iosevka with ligatures support

### ISSUE THREAD

**Issue by GoldsteinE** [be5invis/Iosevka#948]
Despite me explicitly enabling dlig in config, I can't see ligatures in any app.

---

* Your font version: git master
* Your font variant: own
* Your operating system (name and version): Arch Linux
* Your application using Iosevka: wezterm, Firefox, Chromium, VS Code

If you have problem when building Iosevka, please provide these information:

* Your Node.js version: v15.14.0
* Your _otfcc_ version: don't know how to check
* Your `params/parameters.toml`: not modified
* Your `build-plans.toml`: not modified
* Your `private-build-plans.toml`:

 ```toml
[buildPlans.iosevka-gm]
family = "Iosevka GM"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-gm.variants.design]
cv01 = 1
cv02 = 2
cv03 = 1
cv04 = 2
cv05 = 1
cv06 = 1
cv07 = 6
cv08 = 1
cv09 = 1
cv10 = 2
cv11 = 1
cv12 = 1
cv13 = 1
cv14 = 1
cv15 = 1
cv16 = 1
cv17 = 1
cv18 = 1
cv19 = 1
cv20 = 3
cv21 = 1
cv22 = 1
cv23 = 1
cv24 = 1
cv25 = 1
cv26 = 5
cv27 = 1
cv28 = 1
cv29 = 1
cv30 = 1
cv31 = 1
cv32 = 3
cv33 = 1
cv34 = 1
cv35 = 2
cv36 = 1
cv37 = 10
cv38 = 1
cv39 = 1
cv40 = 1
cv41 = 1
cv42 = 1
cv43 = 1
cv44 = 1
cv45 = 1
cv46 = 1
cv47 = 1
cv48 = 1
cv49 = 1
cv50 = 1
cv51 = 4
cv52 = 1
cv53 = 1
cv54 = 1
cv55 = 1
cv56 = 1
cv57 = 4
cv58 = 1
cv59 = 1
cv60 = 1
cv61 = 2
cv62 = 1
cv63 = 2
cv64 = 2
cv65 = 1
cv66 = 1
cv67 = 3
cv68 = 1
cv69 = 1
cv70 = 2
cv71 = 1
cv72 = 3
cv73 = 2
cv74 = 1
cv75 = 1
cv76 = 1
cv77 = 2
cv78 = 2
cv79 = 1
cv80 = 2
cv81 = 1
cv82 = 1
cv83 = 2
cv84 = 1
cv85 = 2
cv86 = 1
cv87 = 1
cv88 = 1
design = ['ligset-dlig']

[buildPlans.iosevka-gm.ligations]
inherits = "dlig"

[buildPlans.iosevka-gm.widths.normal]
shape = 500
menu  = 5
css   = "normal"
  ```
* The detailed error log: no errors.
