### ISSUE TITLE
Italic lowercase Cyrillic Tse doesn't look right with specific settings

### ISSUE THREAD

**Issue by std282** [be5invis/Iosevka#961]
The italic lowercase Cyrillic Tse (`ц`) looks ugly when building with specific settings.

![image](https://user-images.githubusercontent.com/31089329/115278710-72c58380-a14e-11eb-930a-f16f10f16e71.png)

I've found out by occasion that this ugly glyph is not present if you change these settings:

```toml
capital-c = 'unilateral-inward-serifed'
capital-g = 'toothless-rounded-inward-serifed-hooked'
capital-s = 'unilateral-inward-serifed'
c = 'unilateral-inward-serifed'
s = 'unilateral-inward-serifed'
capital-gamma = 'motion-serifed'
latn-epsilon = 'inward-serifed'
```

to those:

```toml
capital-c = 'serifless'
capital-g = 'toothless-rounded-serifless-hooked'
capital-s = 'serifless'
c = 'serifless'
s = 'serifless'
capital-gamma = 'standard'
latn-epsilon = 'serifless'
```

---

Font version: Iosevka 6.0.0-preview.4
Font variant: Custom

`private-build-plans.toml`:
```toml
[buildPlans.iosevka-badcyrtse]
family = "Iosevka BadCyrTse"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka-badcyrtse.variants.design]
capital-a = 'straight-serifless'
capital-b = 'standard-serifless'
capital-c = 'unilateral-inward-serifed'
capital-d = 'standard-serifless'
capital-e = 'standard'
capital-f = 'standard'
capital-g = 'toothless-rounded-inward-serifed-hooked'
capital-h = 'standard'
capital-i = 'serifed'
capital-j = 'serifed'
capital-k = 'straight'
capital-l = 'standard'
capital-m = 'hanging'
capital-n = 'standard'
capital-p = 'closed'
capital-q = 'crossing'
capital-r = 'straight'
capital-s = 'unilateral-inward-serifed'
capital-t = 'serifless'
capital-u = 'toothless-rounded'
capital-v = 'straight'
capital-w = 'straight'
capital-x = 'straight-serifless'
capital-y = 'straight-serifless'
capital-z = 'straight-serifless'
a = 'double-storey-toothless-corner'
b = 'toothless-corner'
c = 'unilateral-inward-serifed'
d = 'toothless-corner-serifless'
e = 'flat-crossbar'
f = 'serifless'
g = 'double-storey'
h = 'straight'
i = 'serifed'
j = 'serifed'
k = 'straight'
l = 'serifed-flat-tailed'
m = 'earless-corner-double-arch'
n = 'earless-corner-straight'
p = 'earless-corner'
q = 'earless-corner'
r = 'earless-corner'
s = 'unilateral-inward-serifed'
t = 'standard'
u = 'toothless-corner'
v = 'straight'
w = 'straight-flat-top'
x = 'straight-serifless'
y = 'straight-turn'
z = 'straight-serifless'
capital-gamma = 'motion-serifed'
latn-epsilon = 'inward-serifed'
lower-iota = 'serifed-flat-tailed'
lower-lambda = 'straight-turn'
cyrl-ka = 'straight'
cyrl-capital-u = 'straight-turn'
zero = 'slashed'
one = 'base'
two = 'curly-neck'
three = 'twoarcs'
four = 'semi-open'
five = 'vertical-upper-left-bar'
six = 'closed-contour'
seven = 'straight-serifless'
eight = 'crossing'
nine = 'closed-contour'
tilde = 'low'
asterisk = 'hex-low'
underscore = 'high'
caret = 'low'
paren = 'normal'
brace = 'straight'
number-sign = 'upright'
ampersand = 'upper-open'
at = 'threefold'
dollar = 'through'
cent = 'through'
percent = 'rings-continuous-slash'
bar = 'natural-slope'
lig-ltgteq = 'slanted'
ascii-single-quote = 'straight'
ascii-grave = 'straight'
question = 'smooth'

[buildPlans.iosevka-badcyrtse.variants.italic]
a = 'single-storey-earless-corner'
f = 'tailed'
i = 'serifed-flat-tailed'
j = 'flat-hook-serifed'
y = 'cursive-flat-hook'
```
